import fs from 'fs';
import path from 'path';
import type { SharedComponentsManifest } from './segment-deduplicator';
import { toPascalCase, toCamelCase, sanitize } from './naming';
import { loadLifecycleStore, getRetiredSelectors } from './selector-lifecycle';

interface GeneratorOptions {
  force?: boolean;
  dryRun?: boolean;
}

interface Selector {
  primary: string;
  fallback?: string[];
  score: number;
  strategy: string;
}

interface Segment {
  id: string;
  type: string;
  selectorHint: string;
  semanticName?: string;
  contentHash?: string;
}

interface Analysis {
  pageName: string;
  domain: string;
  selectors: Selector[];
  segments: Segment[];
}

function ensureDir(dir: string) {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
}

function writeFileSafe(
  filePath: string,
  content: string,
  options: GeneratorOptions
) {
  const exists = fs.existsSync(filePath);

  if (exists && !options.force) {
    console.log(`Skipping existing: ${filePath}`);
    return;
  }

  if (options.dryRun) {
    console.log(`DRY-RUN: Would write ${filePath}`);
    return;
  }

  fs.writeFileSync(filePath, content);
  console.log(`${exists ? 'Overwritten' : 'Created'}: ${filePath}`);
}


export function runFullGenerator(
  analysisPath: string,
  options: GeneratorOptions = {}
) {
  const analysis: Analysis = JSON.parse(
    fs.readFileSync(analysisPath, 'utf-8')
  );

  const pageDir = `src/pages/${analysis.domain}`;
  const componentDir = `src/components/${analysis.domain}`;

  ensureDir(pageDir);
  ensureDir(componentDir);

  // ── Feature 1.8: Load shared-components manifest (written by --dedup pass) ──
  const manifestFilePath = path.join('migration-analysis', analysis.domain, 'shared-components.manifest.json');
  const sharedManifest = fs.existsSync(manifestFilePath)
    ? JSON.parse(fs.readFileSync(manifestFilePath, 'utf-8')) as import('./segment-deduplicator').SharedComponentsManifest
    : null;

  // ── T3.6: Filter out retired selectors ──
  const lifecycleStore = loadLifecycleStore();
  const retiredSelectors = new Set(getRetiredSelectors(lifecycleStore));

  if (retiredSelectors.size > 0) {
    const originalCount = analysis.selectors.length;
    analysis.selectors = analysis.selectors.filter(s => !retiredSelectors.has(s.primary));
    const filtered = originalCount - analysis.selectors.length;
    if (filtered > 0) {
      console.log(`T3.6: Filtered ${filtered} retired selector(s)`);
    }
  }

  // Deterministic segment ordering
  const sortedSegments = [...analysis.segments].sort((a, b) => {
    const nameA = a.semanticName || a.id;
    const nameB = b.semanticName || b.id;
    return nameA.localeCompare(nameB);
  });

  sortedSegments.forEach(segment => {
    // Feature 1.8: Skip generation if this segment is covered by a shared component
    if (segment.contentHash && sharedManifest?.components[segment.contentHash]) {
      const sc = sharedManifest.components[segment.contentHash];
      console.log(`Shared (skip): ${sc.sharedClassName}  [hash: ${segment.contentHash}]`);
      return;
    }

    const baseName = segment.semanticName
      ? sanitize(segment.semanticName)
      : toPascalCase(segment.id);

    const className = `${analysis.pageName}${baseName}Component`;

    const componentPath =
      `${componentDir}/${analysis.pageName}.${baseName}.component.ts`;

    const content = `// Auto-generated by CAF — do not create manually (see T2.7 governance lock).
import { Page, Locator } from '@playwright/test';
import { BaseComponent } from '@/core/base/BaseComponent';

export class ${className} extends BaseComponent {

  constructor(page: Page) {
    super(page, '${segment.selectorHint}');
  }

}
`;

    writeFileSafe(componentPath, content, options);
  });

  const registryPath =
    `${componentDir}/${analysis.pageName}.components.ts`;

  const imports = sortedSegments.map(segment => {
    const baseName = segment.semanticName
      ? sanitize(segment.semanticName)
      : toPascalCase(segment.id);
    // Feature 1.8: Reference shared component when manifest entry exists
    if (segment.contentHash && sharedManifest?.components[segment.contentHash]) {
      const sc = sharedManifest.components[segment.contentHash];
      return `import { ${sc.sharedClassName} } from '@/${sc.sharedPath}';`;
    }
    const className = `${analysis.pageName}${baseName}Component`;
    return `import { ${className} } from '@/components/${analysis.domain}/${analysis.pageName}.${baseName}.component';`;
  }).join('\n');

  const properties = sortedSegments.map(segment => {
    const baseName = segment.semanticName
      ? sanitize(segment.semanticName)
      : toPascalCase(segment.id);
    const propName = toCamelCase(baseName);
    // Feature 1.8: Use shared class name in property type when available
    if (segment.contentHash && sharedManifest?.components[segment.contentHash]) {
      const sc = sharedManifest.components[segment.contentHash];
      return `  readonly ${propName}: ${sc.sharedClassName};`;
    }
    const className = `${analysis.pageName}${baseName}Component`;
    return `  readonly ${propName}: ${className};`;
  }).join('\n');

  const initializations = sortedSegments.map(segment => {
    const baseName = segment.semanticName
      ? sanitize(segment.semanticName)
      : toPascalCase(segment.id);
    const propName = toCamelCase(baseName);
    // Feature 1.8: Instantiate shared component class when available
    if (segment.contentHash && sharedManifest?.components[segment.contentHash]) {
      const sc = sharedManifest.components[segment.contentHash];
      return `    this.${propName} = new ${sc.sharedClassName}(page);`;
    }
    const className = `${analysis.pageName}${baseName}Component`;
    return `    this.${propName} = new ${className}(page);`;
  }).join('\n');

  const registryContent = `// Auto-generated by CAF — do not create manually (see T2.7 governance lock).
${imports}

export class ${analysis.pageName}Components {

${properties}

  constructor(page: any) {

${initializations}

  }

}
`;

  writeFileSafe(registryPath, registryContent, options);

  const pagePath =
    `${pageDir}/${analysis.pageName}.page.ts`;

  const pageContent = `// Auto-generated by CAF — do not create manually (see T2.7 governance lock).
import { Page } from '@playwright/test';
import { BasePage } from '@/core/base/BasePage';
import { ${analysis.pageName}Components } from '@/components/${analysis.domain}/${analysis.pageName}.components';

export class ${analysis.pageName}Page extends BasePage {

  readonly components: ${analysis.pageName}Components;

  constructor(protected readonly page: Page) {
    super(page);
    this.components = new ${analysis.pageName}Components(page);
  }

}
`;

  writeFileSafe(pagePath, pageContent, options);

  // ── Feature 1.3: Generate action stub ──────────────────────────────────────
  // Produces src/actions/{domain}/{PageName}.actions.ts.
  // The stub extends BaseAction, wires the constructor, and calls setPage().
  // Respects --safe (default), --force, and --dry-run via writeFileSafe().

  const actionDir = `src/actions/${analysis.domain}`;
  ensureDir(actionDir);

  const actionPath = `${actionDir}/${analysis.pageName}.actions.ts`;
  const actionPageParam = toCamelCase(analysis.pageName);

  const actionContent = `// Auto-generated by CAF — extend this class with your business flows.
// Each method should be 5–15 lines and encode a single business step.
// See BaseAction for runWithNetwork() (API synchronization helper).
import { BaseAction } from '@/core/base/BaseAction';
import { ${analysis.pageName}Page } from '@/pages/${analysis.domain}/${analysis.pageName}.page';

export class ${analysis.pageName}Actions extends BaseAction {

  constructor(private readonly ${actionPageParam}: ${analysis.pageName}Page) {
    super();
    this.setPage(${actionPageParam}.getPage);
  }

  // TODO: Add business flow methods (5–15 lines each).
  // Example:
  //   async clickSomething(): Promise<void> {
  //     await this.${actionPageParam}.someLocator.click();
  //   }

}
`;

  writeFileSafe(actionPath, actionContent, options);

  // ── Feature 2.1: Generate assertion stub ────────────────────────────────────
  // Produces src/assertions/{domain}/{PageName}.assertions.ts.
  // Standalone class (no base class) — matches the existing hand-written pattern.
  // Constructor accepts the generated page object.  Developers extend with
  // additional page/component dependencies as needed.
  // Stub methods are derived from component segment names so reviewers can see
  // which UI regions are covered and fill in real assertions.

  const assertionDir = `src/assertions/${analysis.domain}`;
  ensureDir(assertionDir);

  const assertionPath = `${assertionDir}/${analysis.pageName}.assertions.ts`;
  const assertionPageParam = toCamelCase(analysis.pageName);

  const assertionMethods = sortedSegments.map(segment => {
    const baseName = segment.semanticName
      ? sanitize(segment.semanticName)
      : toPascalCase(segment.id);
    const propName = toCamelCase(baseName);
    return [
      `  /** Verify the ${baseName} component region is visible. */`,
      `  async verify${baseName}Visible(): Promise<void> {`,
      `    await this.${assertionPageParam}.components.${propName}.waitForVisible();`,
      `    // TODO: Add specific locator assertions as needed.`,
      `  }`,
    ].join('\n');
  }).join('\n\n');

  const assertionContent = `// Auto-generated by CAF — extend this class with your verification methods.
// Each method should wrap one or more expect() calls for a single verification concern.
// This class is standalone (no base class). Add page/component constructor params as needed.
import { ${analysis.pageName}Page } from '@/pages/${analysis.domain}/${analysis.pageName}.page';

export class ${analysis.pageName}Assertions {

  constructor(private readonly ${assertionPageParam}: ${analysis.pageName}Page) {}

${assertionMethods}

}
`;

  writeFileSafe(assertionPath, assertionContent, options);
}