// CAF Governance Lock
// Scans src/pages/ and src/components/ for NEW files missing the
// "Auto-generated by CAF" header. Files that existed before governance
// was enabled are recorded in a baseline file and exempted.
//
// Run with --init to generate the initial baseline from current files.
//
// Exit code 0: all new files pass (or --init completed).
// Exit code 1: new manual files detected (list printed to stderr).

import fs from 'fs';
import path from 'path';

const CAF_MARKER = 'Auto-generated by CAF';
const BASELINE_PATH = '.caf-governance-baseline.json';

const GOVERNED_DIRS = ['src/pages', 'src/components'];

const EXEMPT_PATTERNS = [
  /BasePage\.ts$/,
  /BaseComponent\.ts$/,
  /BaseAction\.ts$/,
  /index\.ts$/,
];

function walk(dir: string): string[] {
  if (!fs.existsSync(dir)) return [];
  const results: string[] = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      results.push(...walk(fullPath));
    } else if (entry.isFile() && entry.name.endsWith('.ts')) {
      results.push(fullPath.replace(/\\/g, '/'));
    }
  }
  return results;
}

function isExempt(filePath: string): boolean {
  return EXEMPT_PATTERNS.some(pattern => pattern.test(filePath));
}

function loadBaseline(): Set<string> {
  if (!fs.existsSync(BASELINE_PATH)) return new Set();
  const data = JSON.parse(fs.readFileSync(BASELINE_PATH, 'utf-8'));
  return new Set(data.files as string[]);
}

if (process.argv.includes('--init')) {
  const allFiles: string[] = [];
  for (const dir of GOVERNED_DIRS) {
    for (const filePath of walk(dir)) {
      if (isExempt(filePath)) continue;
      const firstLine = fs.readFileSync(filePath, 'utf-8').split('\n')[0] || '';
      if (!firstLine.includes(CAF_MARKER)) {
        allFiles.push(filePath);
      }
    }
  }
  allFiles.sort();
  fs.writeFileSync(BASELINE_PATH, JSON.stringify({
    description: 'Pre-governance files exempt from CAF marker check.',
    generatedAt: new Date().toISOString(),
    files: allFiles
  }, null, 2));
  console.log(`Governance baseline created: ${allFiles.length} pre-existing files recorded.`);
  process.exit(0);
}

const baseline = loadBaseline();
const violations: string[] = [];

for (const dir of GOVERNED_DIRS) {
  for (const filePath of walk(dir)) {
    if (isExempt(filePath)) continue;
    if (baseline.has(filePath)) continue;

    const firstLine = fs.readFileSync(filePath, 'utf-8').split('\n')[0] || '';
    if (!firstLine.includes(CAF_MARKER)) {
      violations.push(filePath);
    }
  }
}

if (violations.length > 0) {
  console.error(`\nCAF GOVERNANCE VIOLATION: ${violations.length} new file(s) missing "Auto-generated by CAF" header.\n`);
  console.error('These files appear to have been created manually.\n');
  violations.forEach(f => console.error(`  - ${f}`));
  console.error('\nUse "npm run new-flow" to generate pages and components.');
  console.error('If these files are intentionally hand-written, add them to the baseline:');
  console.error(`  npm run check:governance -- --init\n`);
  process.exit(1);
} else {
  console.log('Governance check passed — no unauthorized manual files detected.');
}
