// Auto-generated by CAF
// T4.7: Cross-Environment Selector Comparison
// Compares selector behavior/success across different environments

import fs from 'fs';
import path from 'path';

// ─────────────────────────────────────────────────────────────────────────────
// Configuration
// ─────────────────────────────────────────────────────────────────────────────

const ENV_DATA_DIR = '.caf-env-data';
const COMPARISON_REPORT_FILE = 'cross-env-comparison.json';
const ENVIRONMENTS = ['dev', 'staging', 'prod'] as const;

type Environment = typeof ENVIRONMENTS[number];

// ─────────────────────────────────────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────────────────────────────────────

interface SelectorMetrics {
  selector: string;
  successRate: number;       // 0-100%
  avgResponseTime: number;   // ms
  fallbackRate: number;      // 0-100%
  lastTested: string;
  totalRuns: number;
}

interface EnvironmentSnapshot {
  environment: Environment;
  capturedAt: string;
  baseUrl: string;
  selectors: Record<string, SelectorMetrics>;
}

interface SelectorComparison {
  selector: string;
  status: 'consistent' | 'divergent' | 'missing-in-env';
  environments: {
    env: Environment;
    successRate: number;
    fallbackRate: number;
    present: boolean;
  }[];
  variance: number;               // Standard deviation of success rates
  recommendation: string;
}

interface ComparisonReport {
  timestamp: string;
  environments: Environment[];
  comparisons: SelectorComparison[];
  summary: {
    totalSelectors: number;
    consistent: number;
    divergent: number;
    missingInEnv: number;
    highVarianceCount: number;    // variance > 20%
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// Data Management
// ─────────────────────────────────────────────────────────────────────────────

function ensureEnvDataDir(): void {
  if (!fs.existsSync(ENV_DATA_DIR)) {
    fs.mkdirSync(ENV_DATA_DIR, { recursive: true });
  }
}

function getSnapshotPath(env: Environment): string {
  return path.join(ENV_DATA_DIR, `${env}-snapshot.json`);
}

function loadEnvironmentSnapshot(env: Environment): EnvironmentSnapshot | null {
  const snapshotPath = getSnapshotPath(env);

  if (!fs.existsSync(snapshotPath)) {
    return null;
  }

  return JSON.parse(fs.readFileSync(snapshotPath, 'utf-8'));
}

function saveEnvironmentSnapshot(snapshot: EnvironmentSnapshot): void {
  ensureEnvDataDir();
  const snapshotPath = getSnapshotPath(snapshot.environment);
  fs.writeFileSync(snapshotPath, JSON.stringify(snapshot, null, 2));
}

function loadSelectorUsage(): Map<string, { fallbackUsed: number; primarySuccess: number }> {
  const usageFile = 'selector-usage.json';

  if (!fs.existsSync(usageFile)) {
    return new Map();
  }

  const data = JSON.parse(fs.readFileSync(usageFile, 'utf-8'));
  return new Map(Object.entries(data));
}

// ─────────────────────────────────────────────────────────────────────────────
// Capture Environment Metrics
// ─────────────────────────────────────────────────────────────────────────────

function captureEnvironment(env: Environment, baseUrl: string): EnvironmentSnapshot {
  const usageMap = loadSelectorUsage();
  const selectors: Record<string, SelectorMetrics> = {};

  for (const [selector, usage] of usageMap.entries()) {
    const totalRuns = usage.fallbackUsed + usage.primarySuccess;

    if (totalRuns === 0) continue;

    const successRate = (usage.primarySuccess / totalRuns) * 100;
    const fallbackRate = (usage.fallbackUsed / totalRuns) * 100;

    selectors[selector] = {
      selector,
      successRate: Math.round(successRate * 100) / 100,
      avgResponseTime: 0,          // Would need telemetry integration
      fallbackRate: Math.round(fallbackRate * 100) / 100,
      lastTested: new Date().toISOString(),
      totalRuns,
    };
  }

  return {
    environment: env,
    capturedAt: new Date().toISOString(),
    baseUrl,
    selectors,
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// Comparison Engine
// ─────────────────────────────────────────────────────────────────────────────

function calculateVariance(values: number[]): number {
  if (values.length === 0) return 0;

  const mean = values.reduce((a, b) => a + b, 0) / values.length;
  const squaredDiffs = values.map(v => Math.pow(v - mean, 2));
  const variance = squaredDiffs.reduce((a, b) => a + b, 0) / values.length;

  return Math.sqrt(variance);  // Return standard deviation
}

function compareSelectors(snapshots: EnvironmentSnapshot[]): SelectorComparison[] {
  // Collect all unique selectors
  const allSelectors = new Set<string>();

  for (const snapshot of snapshots) {
    for (const selector of Object.keys(snapshot.selectors)) {
      allSelectors.add(selector);
    }
  }

  const comparisons: SelectorComparison[] = [];

  for (const selector of allSelectors) {
    const envData: SelectorComparison['environments'] = [];
    const successRates: number[] = [];
    let missingCount = 0;

    for (const snapshot of snapshots) {
      const metrics = snapshot.selectors[selector];

      if (metrics) {
        envData.push({
          env: snapshot.environment,
          successRate: metrics.successRate,
          fallbackRate: metrics.fallbackRate,
          present: true,
        });
        successRates.push(metrics.successRate);
      } else {
        envData.push({
          env: snapshot.environment,
          successRate: 0,
          fallbackRate: 0,
          present: false,
        });
        missingCount++;
      }
    }

    const variance = calculateVariance(successRates);

    // Determine status
    let status: SelectorComparison['status'];
    let recommendation: string;

    if (missingCount > 0) {
      status = 'missing-in-env';
      const missingEnvs = envData.filter(e => !e.present).map(e => e.env).join(', ');
      recommendation = `Selector missing in: ${missingEnvs}. Review DOM structure in those environments.`;
    } else if (variance > 20) {
      status = 'divergent';
      const worst = envData.reduce((a, b) => a.successRate < b.successRate ? a : b);
      recommendation = `High variance (${variance.toFixed(1)}%). Investigate ${worst.env} env (${worst.successRate}% success).`;
    } else {
      status = 'consistent';
      recommendation = 'Selector behaves consistently across environments.';
    }

    comparisons.push({
      selector,
      status,
      environments: envData,
      variance: Math.round(variance * 100) / 100,
      recommendation,
    });
  }

  // Sort: divergent first, then missing, then consistent
  const statusOrder = { divergent: 0, 'missing-in-env': 1, consistent: 2 };
  return comparisons.sort((a, b) => statusOrder[a.status] - statusOrder[b.status]);
}

function generateReport(snapshots: EnvironmentSnapshot[]): ComparisonReport {
  const comparisons = compareSelectors(snapshots);

  const summary = {
    totalSelectors: comparisons.length,
    consistent: comparisons.filter(c => c.status === 'consistent').length,
    divergent: comparisons.filter(c => c.status === 'divergent').length,
    missingInEnv: comparisons.filter(c => c.status === 'missing-in-env').length,
    highVarianceCount: comparisons.filter(c => c.variance > 20).length,
  };

  return {
    timestamp: new Date().toISOString(),
    environments: snapshots.map(s => s.environment),
    comparisons,
    summary,
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// CLI Entry Point
// ─────────────────────────────────────────────────────────────────────────────

function main() {
  const args = process.argv.slice(2);

  const capture = args.includes('--capture');
  const compare = args.includes('--compare');
  const ciMode = args.includes('--ci');

  let env: Environment | undefined;
  let baseUrl = '';

  const envIdx = args.indexOf('--env');
  if (envIdx !== -1 && args[envIdx + 1]) {
    const envArg = args[envIdx + 1] as Environment;
    if (ENVIRONMENTS.includes(envArg)) {
      env = envArg;
    }
  }

  const urlIdx = args.indexOf('--url');
  if (urlIdx !== -1 && args[urlIdx + 1]) {
    baseUrl = args[urlIdx + 1];
  }

  console.log('═══════════════════════════════════════════════════════════════');
  console.log('  T4.7: Cross-Environment Selector Comparison');
  console.log('═══════════════════════════════════════════════════════════════');

  // Capture mode
  if (capture) {
    if (!env) {
      console.log('\n⚠ Environment required: --env <dev|staging|prod>');
      process.exit(1);
    }

    if (!baseUrl) {
      console.log('\n⚠ Base URL required: --url <https://...>');
      process.exit(1);
    }

    const snapshot = captureEnvironment(env, baseUrl);
    saveEnvironmentSnapshot(snapshot);

    console.log(`\n✓ Captured ${env} environment metrics`);
    console.log(`  Selectors: ${Object.keys(snapshot.selectors).length}`);
    console.log(`  Base URL: ${baseUrl}`);
    console.log(`  Saved to: ${getSnapshotPath(env)}`);
    process.exit(0);
  }

  // Compare mode (default)
  if (compare || (!capture && !compare)) {
    const snapshots: EnvironmentSnapshot[] = [];

    for (const e of ENVIRONMENTS) {
      const snapshot = loadEnvironmentSnapshot(e);
      if (snapshot) {
        snapshots.push(snapshot);
      }
    }

    if (snapshots.length < 2) {
      console.log('\n⚠ At least 2 environment snapshots required for comparison.');
      console.log('  Capture snapshots with: npm run check:cross-env -- --capture --env <env> --url <url>');
      console.log(`\n  Available: ${snapshots.map(s => s.environment).join(', ') || 'none'}`);
      process.exit(ciMode ? 0 : 1);
    }

    console.log(`\nComparing ${snapshots.length} environments: ${snapshots.map(s => s.environment).join(', ')}`);

    const report = generateReport(snapshots);

    // Display results
    console.log('\n┌──────────────────────────────────────────────────────────────┐');
    console.log('│ Selector                     │ Status      │ Variance │ Rec  │');
    console.log('├──────────────────────────────────────────────────────────────┤');

    for (const comp of report.comparisons.slice(0, 20)) {
      const selDisplay = comp.selector.substring(0, 28).padEnd(28);
      const statusDisplay = comp.status.padEnd(11);
      const varDisplay = `${comp.variance.toFixed(1)}%`.padStart(8);
      const recDisplay = comp.recommendation.substring(0, 4);
      console.log(`│ ${selDisplay} │ ${statusDisplay} │ ${varDisplay} │ ${recDisplay} │`);
    }

    if (report.comparisons.length > 20) {
      console.log(`│ ... and ${report.comparisons.length - 20} more selectors`);
    }

    console.log('└──────────────────────────────────────────────────────────────┘');

    console.log('\nSummary:');
    console.log(`  Total selectors:   ${report.summary.totalSelectors}`);
    console.log(`  Consistent:        ${report.summary.consistent}`);
    console.log(`  Divergent:         ${report.summary.divergent}`);
    console.log(`  Missing in env:    ${report.summary.missingInEnv}`);
    console.log(`  High variance:     ${report.summary.highVarianceCount}`);

    // Save report
    fs.writeFileSync(COMPARISON_REPORT_FILE, JSON.stringify(report, null, 2));
    console.log(`\nReport saved to ${COMPARISON_REPORT_FILE}`);

    // CI mode exit
    if (ciMode && report.summary.divergent > 0) {
      console.log('\n✗ CROSS-ENV CHECK: FAILED (divergent selectors detected)');
      process.exit(1);
    }

    console.log('\n✓ CROSS-ENV CHECK: PASS');
  }
}

// Guard CLI entry point
if (require.main === module) {
  main();
}

// Export for use in other modules
export { loadEnvironmentSnapshot, compareSelectors, ComparisonReport, SelectorComparison };
