// Auto-generated by CAF
// T4.1: DOM Drift Predictive Alerting
// Predicts selector breakage based on historical DOM change patterns

import fs from 'fs';
import path from 'path';
import { computeDiff, extractElements, DiffResult } from './dom-diff-impact';

// ─────────────────────────────────────────────────────────────────────────────
// Configuration
// ─────────────────────────────────────────────────────────────────────────────

const SNAPSHOTS_DIR = '.caf-dom-snapshots';
const DRIFT_STATE_FILE = '.caf-drift-state.json';
const MAX_SNAPSHOTS = 10;                    // Keep last N snapshots per page
const VOLATILITY_THRESHOLD = 0.5;            // At-risk if volatility >= 50%
const CRITICAL_VOLATILITY_THRESHOLD = 0.7;   // Critical if volatility >= 70%
const PREDICTION_WINDOW = 5;                 // Use last N snapshots for prediction

// ─────────────────────────────────────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────────────────────────────────────

interface SnapshotMeta {
  timestamp: string;
  elementCount: number;
  hash: string;
}

interface SelectorHistory {
  selector: string;
  changes: {
    timestamp: string;
    changeType: 'stable' | 'modified' | 'removed' | 'restored';
  }[];
  volatilityScore: number;        // 0-1, higher = more volatile
  lastSeen: string;
  status: 'stable' | 'at-risk' | 'critical';
}

interface DriftState {
  version: string;
  updatedAt: string;
  pages: Record<string, {
    snapshots: SnapshotMeta[];
    selectors: Record<string, SelectorHistory>;
  }>;
}

interface PredictionResult {
  selector: string;
  riskLevel: 'low' | 'medium' | 'high' | 'critical';
  volatilityScore: number;
  changeFrequency: number;         // Changes per snapshot
  prediction: string;
  confidence: number;              // 0-100%
}

// ─────────────────────────────────────────────────────────────────────────────
// State Management
// ─────────────────────────────────────────────────────────────────────────────

function loadDriftState(): DriftState {
  if (!fs.existsSync(DRIFT_STATE_FILE)) {
    return {
      version: '1.0',
      updatedAt: new Date().toISOString(),
      pages: {},
    };
  }

  return JSON.parse(fs.readFileSync(DRIFT_STATE_FILE, 'utf-8'));
}

function saveDriftState(state: DriftState): void {
  state.updatedAt = new Date().toISOString();
  fs.writeFileSync(DRIFT_STATE_FILE, JSON.stringify(state, null, 2));
}

function ensureSnapshotsDir(): void {
  if (!fs.existsSync(SNAPSHOTS_DIR)) {
    fs.mkdirSync(SNAPSHOTS_DIR, { recursive: true });
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// Snapshot Management
// ─────────────────────────────────────────────────────────────────────────────

function hashContent(content: string): string {
  let hash = 0;
  for (let i = 0; i < content.length; i++) {
    const char = content.charCodeAt(i);
    hash = ((hash << 5) - hash) + char;
    hash = hash & hash;
  }
  return Math.abs(hash).toString(16).padStart(8, '0');
}

function saveSnapshot(pageName: string, htmlContent: string, state: DriftState): SnapshotMeta {
  ensureSnapshotsDir();

  const timestamp = new Date().toISOString();
  const hash = hashContent(htmlContent);
  const elements = extractElements(htmlContent);

  // Initialize page if needed
  if (!state.pages[pageName]) {
    state.pages[pageName] = {
      snapshots: [],
      selectors: {},
    };
  }

  const pageState = state.pages[pageName];

  // Check if this exact snapshot already exists
  const existingSnapshot = pageState.snapshots.find(s => s.hash === hash);
  if (existingSnapshot) {
    return existingSnapshot;
  }

  // Save snapshot file
  const snapshotPath = path.join(SNAPSHOTS_DIR, `${pageName}-${Date.now()}.html`);
  fs.writeFileSync(snapshotPath, htmlContent);

  const meta: SnapshotMeta = {
    timestamp,
    elementCount: elements.size,
    hash,
  };

  // Add to snapshots list
  pageState.snapshots.push(meta);

  // Trim old snapshots and delete their files
  while (pageState.snapshots.length > MAX_SNAPSHOTS) {
    const removed = pageState.snapshots.shift();
    // Delete corresponding .html files (find oldest files for this page)
    if (removed) {
      const files = fs.readdirSync(SNAPSHOTS_DIR)
        .filter(f => f.startsWith(pageName) && f.endsWith('.html'))
        .sort();
      // Delete the oldest file (first in sorted list)
      if (files.length > MAX_SNAPSHOTS) {
        const oldestFile = path.join(SNAPSHOTS_DIR, files[0]);
        try {
          fs.unlinkSync(oldestFile);
        } catch {
          // Ignore file deletion errors
        }
      }
    }
  }

  return meta;
}

// ─────────────────────────────────────────────────────────────────────────────
// Volatility Analysis
// ─────────────────────────────────────────────────────────────────────────────

function updateSelectorHistory(
  pageName: string,
  diff: DiffResult,
  state: DriftState,
  timestamp: string
): void {
  const pageState = state.pages[pageName];
  if (!pageState) return;

  // Track removed selectors
  for (const removed of diff.removed) {
    const history = pageState.selectors[removed.selector] || {
      selector: removed.selector,
      changes: [],
      volatilityScore: 0,
      lastSeen: timestamp,
      status: 'stable' as const,
    };

    history.changes.push({
      timestamp,
      changeType: 'removed',
    });

    pageState.selectors[removed.selector] = history;
  }

  // Track modified selectors
  for (const modified of diff.modified) {
    const history = pageState.selectors[modified.selector] || {
      selector: modified.selector,
      changes: [],
      volatilityScore: 0,
      lastSeen: timestamp,
      status: 'stable' as const,
    };

    history.changes.push({
      timestamp,
      changeType: 'modified',
    });
    history.lastSeen = timestamp;

    pageState.selectors[modified.selector] = history;
  }

  // Track added selectors (restored)
  for (const added of diff.added) {
    const existing = pageState.selectors[added.selector];
    if (existing && existing.changes.some(c => c.changeType === 'removed')) {
      existing.changes.push({
        timestamp,
        changeType: 'restored',
      });
      existing.lastSeen = timestamp;
    }
  }

  // Build set of selectors that changed in this snapshot
  const changedSelectors = new Set<string>([
    ...diff.removed.map(r => r.selector),
    ...diff.modified.map(m => m.selector),
    ...diff.added.map(a => a.selector),
  ]);

  // Track 'stable' entries for existing tracked selectors that didn't change
  // This is critical for accurate volatility calculation
  for (const [selector, history] of Object.entries(pageState.selectors)) {
    if (!changedSelectors.has(selector) && history.status !== 'stable') {
      // This selector was tracked before but didn't change - mark as stable
      history.changes.push({
        timestamp,
        changeType: 'stable',
      });
      history.lastSeen = timestamp;
    }
  }

  // Recalculate volatility scores
  for (const history of Object.values(pageState.selectors)) {
    history.volatilityScore = calculateVolatility(history);
    history.status = determineStatus(history);
  }
}

function calculateVolatility(history: SelectorHistory): number {
  const recentChanges = history.changes.slice(-PREDICTION_WINDOW);

  if (recentChanges.length === 0) {
    return 0;
  }

  // Count non-stable changes
  const instabilities = recentChanges.filter(c => c.changeType !== 'stable').length;

  // Use actual sample size when fewer than PREDICTION_WINDOW entries exist
  const sampleSize = Math.min(recentChanges.length, PREDICTION_WINDOW);
  return instabilities / sampleSize;
}

function determineStatus(history: SelectorHistory): 'stable' | 'at-risk' | 'critical' {
  if (history.volatilityScore >= CRITICAL_VOLATILITY_THRESHOLD) {
    return 'critical';
  }
  if (history.volatilityScore >= VOLATILITY_THRESHOLD) {
    return 'at-risk';
  }
  return 'stable';
}

// ─────────────────────────────────────────────────────────────────────────────
// Prediction Engine
// ─────────────────────────────────────────────────────────────────────────────

function generatePredictions(state: DriftState): PredictionResult[] {
  const predictions: PredictionResult[] = [];

  for (const [pageName, pageState] of Object.entries(state.pages)) {
    for (const [selector, history] of Object.entries(pageState.selectors)) {
      if (history.status === 'stable') continue;

      const changeFrequency = history.changes.length / Math.max(pageState.snapshots.length, 1);

      let riskLevel: PredictionResult['riskLevel'] = 'low';
      let prediction = 'Selector appears stable';
      let confidence = 50;

      if (history.status === 'critical') {
        riskLevel = 'critical';
        prediction = 'High probability of breaking in next deployment';
        confidence = Math.min(90, 50 + history.volatilityScore * 50);
      } else if (history.status === 'at-risk') {
        riskLevel = history.volatilityScore > 0.4 ? 'high' : 'medium';
        prediction = 'May become unstable; monitor closely';
        confidence = Math.min(75, 40 + history.volatilityScore * 40);
      }

      // Check for recent removal (strong signal)
      const lastChange = history.changes[history.changes.length - 1];
      if (lastChange?.changeType === 'removed') {
        riskLevel = 'critical';
        prediction = 'Selector was recently removed from DOM';
        confidence = 95;
      }

      predictions.push({
        selector,
        riskLevel,
        volatilityScore: Math.round(history.volatilityScore * 100) / 100,
        changeFrequency: Math.round(changeFrequency * 100) / 100,
        prediction,
        confidence: Math.round(confidence),
      });
    }
  }

  return predictions.sort((a, b) => {
    const order = { critical: 0, high: 1, medium: 2, low: 3 };
    return order[a.riskLevel] - order[b.riskLevel];
  });
}

// ─────────────────────────────────────────────────────────────────────────────
// CLI Entry Point
// ─────────────────────────────────────────────────────────────────────────────

function main() {
  const args = process.argv.slice(2);

  const capture = args.includes('--capture');
  const predict = args.includes('--predict');
  const ciMode = args.includes('--ci');
  const report = args.includes('--report');

  let pageName = 'default';
  let snapshotPath = '';

  const pageIdx = args.indexOf('--page');
  if (pageIdx !== -1 && args[pageIdx + 1]) {
    pageName = args[pageIdx + 1];
  }

  const snapshotIdx = args.indexOf('--snapshot');
  if (snapshotIdx !== -1 && args[snapshotIdx + 1]) {
    snapshotPath = args[snapshotIdx + 1];
  }

  console.log('═══════════════════════════════════════════════════════════════');
  console.log('  T4.1: DOM Drift Predictive Alerting');
  console.log('═══════════════════════════════════════════════════════════════');

  const state = loadDriftState();

  // Capture mode: save new snapshot
  if (capture) {
    if (!snapshotPath || !fs.existsSync(snapshotPath)) {
      console.log('\n⚠ Snapshot file required: --snapshot <file.html>');
      process.exit(1);
    }

    const htmlContent = fs.readFileSync(snapshotPath, 'utf-8');
    const pageState = state.pages[pageName];

    // Compare with previous snapshot if exists
    if (pageState && pageState.snapshots.length > 0) {
      // Find and read previous snapshot
      const prevFiles = fs.readdirSync(SNAPSHOTS_DIR)
        .filter(f => f.startsWith(pageName) && f.endsWith('.html'))
        .sort()
        .reverse();

      if (prevFiles.length > 0) {
        const prevContent = fs.readFileSync(
          path.join(SNAPSHOTS_DIR, prevFiles[0]),
          'utf-8'
        );

        const oldElements = extractElements(prevContent);
        const newElements = extractElements(htmlContent);
        const diff = computeDiff(oldElements, newElements);

        updateSelectorHistory(pageName, diff, state, new Date().toISOString());

        console.log('\nDiff from previous snapshot:');
        console.log(`  Added:    ${diff.added.length}`);
        console.log(`  Removed:  ${diff.removed.length}`);
        console.log(`  Modified: ${diff.modified.length}`);
      }
    }

    const meta = saveSnapshot(pageName, htmlContent, state);
    saveDriftState(state);

    console.log(`\n✓ Snapshot captured for "${pageName}"`);
    console.log(`  Elements: ${meta.elementCount}`);
    console.log(`  Hash: ${meta.hash}`);
  }

  // Predict mode: analyze and predict
  if (predict || report || (!capture && !predict)) {
    const predictions = generatePredictions(state);

    if (predictions.length === 0) {
      console.log('\n✓ No at-risk selectors detected.');
      console.log('  Capture more snapshots to build prediction history.');
    } else {
      console.log('\nRisk Predictions:');
      console.log('┌──────────────────────────────────────────────────────────────┐');
      console.log('│ Selector                     │ Risk     │ Volatility │ Conf  │');
      console.log('├──────────────────────────────────────────────────────────────┤');

      for (const pred of predictions) {
        const selDisplay = pred.selector.substring(0, 28).padEnd(28);
        const riskDisplay = pred.riskLevel.toUpperCase().padEnd(8);
        const volDisplay = (pred.volatilityScore * 100).toFixed(0).padStart(3) + '%     ';
        const confDisplay = `${pred.confidence}%`.padStart(5);
        console.log(`│ ${selDisplay} │ ${riskDisplay} │ ${volDisplay} │ ${confDisplay} │`);
      }

      console.log('└──────────────────────────────────────────────────────────────┘');

      const critical = predictions.filter(p => p.riskLevel === 'critical').length;
      const high = predictions.filter(p => p.riskLevel === 'high').length;

      console.log(`\nSummary: ${critical} critical, ${high} high risk`);

      if (ciMode && critical > 0) {
        console.log('\n✗ DRIFT CHECK: FAILED (critical risk selectors detected)');
        process.exit(1);
      }
    }
  }

  // Full report
  if (report) {
    console.log('\n───────────────────────────────────────────────────────────────');
    console.log('Detailed State:');

    for (const [pageName, pageState] of Object.entries(state.pages)) {
      console.log(`\nPage: ${pageName}`);
      console.log(`  Snapshots: ${pageState.snapshots.length}`);
      console.log(`  Tracked selectors: ${Object.keys(pageState.selectors).length}`);

      const atRisk = Object.values(pageState.selectors).filter(
        s => s.status !== 'stable'
      );

      if (atRisk.length > 0) {
        console.log('  At-risk selectors:');
        for (const sel of atRisk) {
          console.log(`    - ${sel.selector} (${sel.status}, volatility: ${(sel.volatilityScore * 100).toFixed(0)}%)`);
        }
      }
    }
  }

  console.log('\n✓ DRIFT CHECK: PASS');
}

// Guard CLI entry point
if (require.main === module) {
  main();
}

// Export for use in other modules
export { loadDriftState, generatePredictions, PredictionResult };
