// Auto-generated by CAF
// T4.2: DOM Diff Impact Analysis
// Compares DOM snapshots and identifies impacted selectors

import fs from 'fs';
import path from 'path';
import * as cheerio from 'cheerio';

// ─────────────────────────────────────────────────────────────────────────────
// Configuration
// ─────────────────────────────────────────────────────────────────────────────

const ANALYSIS_DIR = 'migration-analysis';
const REPORT_FILE = 'dom-diff-report.json';

// ─────────────────────────────────────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────────────────────────────────────

interface ElementInfo {
  tag: string;
  id?: string;
  testId?: string;
  name?: string;
  role?: string;
  selector: string;
  attributes: Record<string, string>;
  path: string;
}

interface ModifiedElement {
  selector: string;
  path: string;
  changeType: 'attribute' | 'children' | 'structure';
  oldValue?: string;
  newValue?: string;
}

interface DiffResult {
  added: ElementInfo[];
  removed: ElementInfo[];
  modified: ModifiedElement[];
}

type ImpactLevel = 'high' | 'medium' | 'low';

interface ImpactedSelector {
  selector: string;
  impact: ImpactLevel;
  reason: string;
  affectedFiles: string[];
}

interface SelectorCandidate {
  primary: string;
  fallback: string[];
  score: number;
  strategy: string;
}

interface AnalysisFile {
  pageName: string;
  domain: string;
  selectors: SelectorCandidate[];
}

interface DiffReport {
  timestamp: string;
  oldSnapshot: string;
  newSnapshot: string;
  changes: {
    added: number;
    removed: number;
    modified: number;
  };
  impactedSelectors: ImpactedSelector[];
  summary: {
    high: number;
    medium: number;
    low: number;
    total: number;
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// DOM Parsing
// ─────────────────────────────────────────────────────────────────────────────

function extractElements(html: string): Map<string, ElementInfo> {
  const $ = cheerio.load(html);
  const elements = new Map<string, ElementInfo>();

  $('*').each((_, el) => {
    if (el.type !== 'tag') return;

    const $el = $(el);
    const tag = el.name.toLowerCase();

    // Skip non-interactive elements
    if (['html', 'head', 'meta', 'script', 'style', 'link', 'noscript'].includes(tag)) {
      return;
    }

    const id = $el.attr('id');
    const testId = $el.attr('data-testid');
    const name = $el.attr('name');
    const role = $el.attr('role');

    // Build unique key for element identification
    let key = '';
    if (testId) {
      key = `[data-testid="${testId}"]`;
    } else if (id) {
      key = `#${id}`;
    } else if (name && ['input', 'select', 'textarea'].includes(tag)) {
      key = `${tag}[name="${name}"]`;
    } else if (role) {
      key = `[role="${role}"]`;
    } else {
      // Use path-based key for elements without stable identifiers
      const parents: string[] = [];
      $el.parents().each((_, parent) => {
        if (parent.type === 'tag') {
          const pId = $(parent).attr('id');
          if (pId) {
            parents.unshift(`#${pId}`);
          } else {
            parents.unshift(parent.name);
          }
        }
      });
      // Calculate nth-of-type correctly by counting only siblings of same tag
      const sameTagSiblings = $el.parent().children(tag);
      const nthOfType = sameTagSiblings.index($el) + 1;
      key = `${parents.join(' > ')} > ${tag}:nth-of-type(${nthOfType})`;
    }

    // Collect all attributes
    const attributes: Record<string, string> = {};
    if (el.attribs) {
      for (const [attrName, attrValue] of Object.entries(el.attribs)) {
        attributes[attrName] = attrValue;
      }
    }

    elements.set(key, {
      tag,
      id,
      testId,
      name,
      role,
      selector: key,
      attributes,
      path: key,
    });
  });

  return elements;
}

// ─────────────────────────────────────────────────────────────────────────────
// Diff Engine
// ─────────────────────────────────────────────────────────────────────────────

function computeDiff(oldElements: Map<string, ElementInfo>, newElements: Map<string, ElementInfo>): DiffResult {
  const added: ElementInfo[] = [];
  const removed: ElementInfo[] = [];
  const modified: ModifiedElement[] = [];

  // Find removed elements
  for (const [key, oldEl] of oldElements.entries()) {
    if (!newElements.has(key)) {
      removed.push(oldEl);
    }
  }

  // Find added elements
  for (const [key, newEl] of newElements.entries()) {
    if (!oldElements.has(key)) {
      added.push(newEl);
    }
  }

  // Find modified elements
  for (const [key, oldEl] of oldElements.entries()) {
    const newEl = newElements.get(key);
    if (!newEl) continue;

    // Check for attribute changes
    const oldAttrs = JSON.stringify(sortObject(oldEl.attributes));
    const newAttrs = JSON.stringify(sortObject(newEl.attributes));

    if (oldAttrs !== newAttrs) {
      modified.push({
        selector: key,
        path: oldEl.path,
        changeType: 'attribute',
        oldValue: oldAttrs,
        newValue: newAttrs,
      });
    }
  }

  return { added, removed, modified };
}

function sortObject(obj: Record<string, string>): Record<string, string> {
  const sorted: Record<string, string> = {};
  for (const key of Object.keys(obj).sort()) {
    sorted[key] = obj[key];
  }
  return sorted;
}

// ─────────────────────────────────────────────────────────────────────────────
// Selector Impact Analysis
// ─────────────────────────────────────────────────────────────────────────────

function loadAnalysisFiles(): Map<string, { selectors: SelectorCandidate[]; files: string[] }> {
  const analysisMap = new Map<string, { selectors: SelectorCandidate[]; files: string[] }>();

  if (!fs.existsSync(ANALYSIS_DIR)) {
    return analysisMap;
  }

  function scanDir(dir: string) {
    const entries = fs.readdirSync(dir, { withFileTypes: true });

    for (const entry of entries) {
      const fullPath = path.join(dir, entry.name);

      if (entry.isDirectory()) {
        scanDir(fullPath);
      } else if (entry.name.endsWith('.analysis.json')) {
        try {
          const content = fs.readFileSync(fullPath, 'utf-8');
          const analysis: AnalysisFile = JSON.parse(content);

          for (const selector of analysis.selectors) {
            const existing = analysisMap.get(selector.primary);
            if (existing) {
              // Selector exists in multiple files - add to both arrays
              existing.selectors.push(selector);
              if (!existing.files.includes(fullPath)) {
                existing.files.push(fullPath);
              }
            } else {
              analysisMap.set(selector.primary, {
                selectors: [selector],
                files: [fullPath],
              });
            }

            // Also track fallbacks
            for (const fallback of selector.fallback || []) {
              const existingFallback = analysisMap.get(fallback);
              if (existingFallback) {
                if (!existingFallback.files.includes(fullPath)) {
                  existingFallback.files.push(fullPath);
                }
              } else {
                analysisMap.set(fallback, {
                  selectors: [selector],
                  files: [fullPath],
                });
              }
            }
          }
        } catch {
          // Skip invalid files
        }
      }
    }
  }

  scanDir(ANALYSIS_DIR);
  return analysisMap;
}

function analyzeImpact(
  diff: DiffResult,
  analysisMap: Map<string, { selectors: SelectorCandidate[]; files: string[] }>
): ImpactedSelector[] {
  const impacted: ImpactedSelector[] = [];
  const seen = new Set<string>();

  // High impact: removed elements
  for (const removed of diff.removed) {
    const selector = removed.selector;
    if (seen.has(selector)) continue;

    const analysisEntry = analysisMap.get(selector);
    if (analysisEntry) {
      seen.add(selector);
      impacted.push({
        selector,
        impact: 'high',
        reason: 'Element removed from DOM',
        affectedFiles: analysisEntry.files,
      });
    }
  }

  // Medium impact: modified elements
  for (const modified of diff.modified) {
    const selector = modified.selector;
    if (seen.has(selector)) continue;

    const analysisEntry = analysisMap.get(selector);
    if (analysisEntry) {
      seen.add(selector);
      impacted.push({
        selector,
        impact: 'medium',
        reason: `Attributes changed (${modified.changeType})`,
        affectedFiles: analysisEntry.files,
      });
    }
  }

  // Low impact: added elements near existing selectors
  // (Simplified: check if added element has similar parent path)
  for (const added of diff.added) {
    const pathParts = added.path.split(' > ');
    if (pathParts.length < 2) continue;

    const parentPath = pathParts.slice(0, -1).join(' > ');

    for (const [selector, entry] of analysisMap.entries()) {
      if (seen.has(selector)) continue;

      if (selector.includes(parentPath) || parentPath.includes(selector.split(' ')[0])) {
        seen.add(selector);
        impacted.push({
          selector,
          impact: 'low',
          reason: 'New element added nearby',
          affectedFiles: entry.files,
        });
        break;
      }
    }
  }

  return impacted.sort((a, b) => {
    const order = { high: 0, medium: 1, low: 2 };
    return order[a.impact] - order[b.impact];
  });
}

// ─────────────────────────────────────────────────────────────────────────────
// Report Generation
// ─────────────────────────────────────────────────────────────────────────────

function generateReport(
  oldPath: string,
  newPath: string,
  diff: DiffResult,
  impacted: ImpactedSelector[]
): DiffReport {
  const summary = {
    high: impacted.filter(i => i.impact === 'high').length,
    medium: impacted.filter(i => i.impact === 'medium').length,
    low: impacted.filter(i => i.impact === 'low').length,
    total: impacted.length,
  };

  return {
    timestamp: new Date().toISOString(),
    oldSnapshot: oldPath,
    newSnapshot: newPath,
    changes: {
      added: diff.added.length,
      removed: diff.removed.length,
      modified: diff.modified.length,
    },
    impactedSelectors: impacted,
    summary,
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// CLI Entry Point
// ─────────────────────────────────────────────────────────────────────────────

function main() {
  const args = process.argv.slice(2);

  // Parse arguments
  let oldPath = 'dom-old.html';
  let newPath = 'dom-new.html';
  const ciMode = args.includes('--ci');

  const oldIdx = args.indexOf('--old');
  if (oldIdx !== -1 && args[oldIdx + 1]) {
    oldPath = args[oldIdx + 1];
  }

  const newIdx = args.indexOf('--new');
  if (newIdx !== -1 && args[newIdx + 1]) {
    newPath = args[newIdx + 1];
  }

  console.log('═══════════════════════════════════════════════════════════════');
  console.log('  T4.2: DOM Diff Impact Analysis');
  console.log('═══════════════════════════════════════════════════════════════');

  // Validate files exist
  if (!fs.existsSync(oldPath)) {
    console.log(`\n⚠ Old snapshot not found: ${oldPath}`);
    console.log('Usage: npm run check:dom-diff -- --old <old.html> --new <new.html>');
    process.exit(ciMode ? 0 : 1);
  }

  if (!fs.existsSync(newPath)) {
    console.log(`\n⚠ New snapshot not found: ${newPath}`);
    console.log('Usage: npm run check:dom-diff -- --old <old.html> --new <new.html>');
    process.exit(ciMode ? 0 : 1);
  }

  console.log(`\nComparing: ${oldPath} → ${newPath}`);

  // Parse DOMs
  const oldHTML = fs.readFileSync(oldPath, 'utf-8');
  const newHTML = fs.readFileSync(newPath, 'utf-8');

  const oldElements = extractElements(oldHTML);
  const newElements = extractElements(newHTML);

  console.log(`\nParsed ${oldElements.size} elements (old) → ${newElements.size} elements (new)`);

  // Compute diff
  const diff = computeDiff(oldElements, newElements);

  console.log('\nStructural Changes:');
  console.log(`  Added:    ${diff.added.length} elements`);
  console.log(`  Removed:  ${diff.removed.length} elements`);
  console.log(`  Modified: ${diff.modified.length} elements`);

  // Load analysis and compute impact
  const analysisMap = loadAnalysisFiles();
  console.log(`\nLoaded ${analysisMap.size} selectors from analysis files.`);

  const impacted = analyzeImpact(diff, analysisMap);

  // Display impacted selectors
  if (impacted.length === 0) {
    console.log('\n✓ No tracked selectors impacted by DOM changes.');
  } else {
    console.log('\nImpacted Selectors:');
    console.log('┌──────────────────────────────────────────────────────────────┐');
    console.log('│ Selector                          │ Impact │ Reason         │');
    console.log('├──────────────────────────────────────────────────────────────┤');

    for (const item of impacted) {
      const selectorDisplay = item.selector.substring(0, 33).padEnd(33);
      const impactDisplay = item.impact.toUpperCase().padEnd(6);
      const reasonDisplay = item.reason.substring(0, 14).padEnd(14);
      console.log(`│ ${selectorDisplay} │ ${impactDisplay} │ ${reasonDisplay} │`);
    }

    console.log('└──────────────────────────────────────────────────────────────┘');
  }

  // Generate report
  const report = generateReport(oldPath, newPath, diff, impacted);

  console.log(`\nSummary: ${report.summary.total} selectors at risk`);
  console.log(`  High:   ${report.summary.high}`);
  console.log(`  Medium: ${report.summary.medium}`);
  console.log(`  Low:    ${report.summary.low}`);

  // Write report
  fs.writeFileSync(REPORT_FILE, JSON.stringify(report, null, 2));
  console.log(`\nReport written to ${REPORT_FILE}`);

  // CI mode exit code
  if (ciMode && report.summary.high > 0) {
    console.log('\n✗ DOM DIFF CHECK: FAILED (high-impact changes detected)');
    process.exit(1);
  }

  console.log('\n✓ DOM DIFF CHECK: PASS');
}

// Guard CLI entry point
if (require.main === module) {
  main();
}

// Export for use in other modules
export { computeDiff, extractElements, analyzeImpact, DiffResult, ImpactedSelector };
