// Auto-generated by CAF
// T5.5: Full Flake Auto-Triage from Playwright Traces
// Parses trace files to extract rich failure context and provide actionable triage

import fs from 'fs';
import path from 'path';
import zlib from 'zlib';

// ─────────────────────────────────────────────────────────────────────────────
// Configuration
// ─────────────────────────────────────────────────────────────────────────────

const TRACES_DIR = 'traces';
const TEST_RESULTS_FILE = 'test-results.json';
const ANALYSIS_DIR = 'migration-analysis';
const LIFECYCLE_FILE = '.caf-selector-lifecycle.json';
const OUTPUT_FILE = 'flake-triage.json';

// ─────────────────────────────────────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────────────────────────────────────

type FlakeCategory =
  // Existing (T3.4)
  | 'timeout'
  | 'visibility'
  | 'detached'
  | 'strict'
  // New (T5.5)
  | 'selector_changed'
  | 'element_relocated'
  | 'timing_race'
  | 'stale_reference'
  | 'network_dependency'
  | 'other';

interface ActionContext {
  action: string;
  targetSelector: string;
  timestamp: number;
  duration?: number;
  screenshotPath?: string;
}

interface DomContext {
  elementExists: boolean;
  elementVisible: boolean;
  matchCount: number;
}

interface Remediation {
  suggestion: string;
  confidence: 'high' | 'medium' | 'low';
  autoFixable: boolean;
}

interface SelectorMeta {
  score: number;
  strategy: string;
  lifecycleState: 'active' | 'watch' | 'retired' | 'unknown';
}

interface TriageResult {
  testName: string;
  testFile: string;
  failureType: FlakeCategory;
  errorMessage: string;
  selector?: string;
  selectorMeta?: SelectorMeta;
  actionContext?: ActionContext;
  domContext?: DomContext;
  remediation: Remediation;
}

interface FlakeTriageReport {
  version: string;
  generatedAt: string;
  summary: {
    totalFailures: number;
    byCategory: Record<string, number>;
    autoFixable: number;
    selectorIssues: number;
  };
  failures: TriageResult[];
}

// Playwright test-results.json types
interface TestResult {
  status: 'passed' | 'failed' | 'timedOut' | 'skipped';
  error?: {
    message?: string;
    stack?: string;
  };
  attachments?: Array<{
    name: string;
    path?: string;
    contentType: string;
  }>;
}

interface TestCase {
  title: string;
  file?: string;
  results: TestResult[];
}

interface TestSuite {
  title: string;
  file?: string;
  tests?: TestCase[];
  suites?: TestSuite[];
}

interface PlaywrightResults {
  suites?: TestSuite[];
}

// Trace event types (simplified - Playwright internal format)
interface TraceEvent {
  type: string;
  timestamp?: number;
  duration?: number;
  params?: Record<string, unknown>;
  stack?: string[];
  error?: {
    message?: string;
    stack?: string;
  };
}

// Analysis file types
interface SelectorCandidate {
  primary: string;
  fallback: string[];
  score: number;
  strategy: string;
  tier: string;
}

interface AnalysisFile {
  pageName: string;
  selectors: SelectorCandidate[];
}

// Lifecycle types
interface SelectorLifecycle {
  selector: string;
  state: 'active' | 'watch' | 'retired';
  consecutiveFallbacks: number;
  lastScore: number;
  history: Array<{ timestamp: string; action: string }>;
}

interface LifecycleStore {
  version: string;
  updatedAt: string;
  selectors: Record<string, SelectorLifecycle>;
}

// ─────────────────────────────────────────────────────────────────────────────
// Selector Metadata Loading
// ─────────────────────────────────────────────────────────────────────────────

function loadSelectorMetadata(): Map<string, { score: number; strategy: string }> {
  const metadata = new Map<string, { score: number; strategy: string }>();

  if (!fs.existsSync(ANALYSIS_DIR)) {
    return metadata;
  }

  function scanDir(dir: string) {
    const entries = fs.readdirSync(dir, { withFileTypes: true });

    for (const entry of entries) {
      const fullPath = path.join(dir, entry.name);

      if (entry.isDirectory()) {
        scanDir(fullPath);
      } else if (entry.name.endsWith('.analysis.json')) {
        try {
          const content = fs.readFileSync(fullPath, 'utf-8');
          const analysis: AnalysisFile = JSON.parse(content);

          for (const selector of analysis.selectors || []) {
            metadata.set(selector.primary, {
              score: selector.score,
              strategy: selector.strategy,
            });
          }
        } catch {
          // Skip invalid files
        }
      }
    }
  }

  scanDir(ANALYSIS_DIR);
  return metadata;
}

function loadLifecycleState(): Map<string, 'active' | 'watch' | 'retired'> {
  const states = new Map<string, 'active' | 'watch' | 'retired'>();

  if (!fs.existsSync(LIFECYCLE_FILE)) {
    return states;
  }

  try {
    const store: LifecycleStore = JSON.parse(fs.readFileSync(LIFECYCLE_FILE, 'utf-8'));

    for (const [selector, lifecycle] of Object.entries(store.selectors)) {
      states.set(selector, lifecycle.state);
    }
  } catch {
    // Return empty map on error
  }

  return states;
}

// ─────────────────────────────────────────────────────────────────────────────
// Flake Classification
// ─────────────────────────────────────────────────────────────────────────────

function classifyFlake(errorMessage: string, errorStack?: string): FlakeCategory {
  const msg = errorMessage.toLowerCase();
  const stack = (errorStack || '').toLowerCase();

  // Strict mode - multiple elements matched
  if (msg.includes('strict mode violation') || msg.includes('resolved to')) {
    return 'strict';
  }

  // Timeout variations
  if (msg.includes('timeout') || msg.includes('exceeded')) {
    // Check for network dependency hints
    if (stack.includes('waitforresponse') || stack.includes('waitforurl')) {
      return 'network_dependency';
    }
    // Check for timing race (element appeared late)
    if (msg.includes('waiting for') && msg.includes('to be')) {
      return 'timing_race';
    }
    return 'timeout';
  }

  // Visibility issues
  if (msg.includes('not visible') || msg.includes('hidden') || msg.includes('covered')) {
    return 'visibility';
  }

  // Detached from DOM
  if (msg.includes('detached') || msg.includes('removed from document')) {
    return 'detached';
  }

  // Stale element reference
  if (msg.includes('stale') || msg.includes('no longer attached')) {
    return 'stale_reference';
  }

  // Selector changed (element not found variations)
  if (
    msg.includes('no element matching') ||
    msg.includes('unable to find') ||
    msg.includes('cannot find') ||
    msg.includes('element not found')
  ) {
    return 'selector_changed';
  }

  // Element relocated (position changed)
  if (msg.includes('intercept') || msg.includes('another element')) {
    return 'element_relocated';
  }

  return 'other';
}

// ─────────────────────────────────────────────────────────────────────────────
// Selector Extraction
// ─────────────────────────────────────────────────────────────────────────────

function extractSelector(errorMessage: string): string | undefined {
  // Pattern: locator('selector')
  const locatorMatch = errorMessage.match(/locator\(['"]([^'"]+)['"]\)/);
  if (locatorMatch) {
    return locatorMatch[1];
  }

  // Pattern: selector "selector"
  const selectorMatch = errorMessage.match(/selector\s+["']([^"']+)["']/i);
  if (selectorMatch) {
    return selectorMatch[1];
  }

  // Pattern: getByRole(...) - extract the description
  const roleMatch = errorMessage.match(/getBy(Role|Text|Label|Placeholder|TestId)\(['"]([^'"]+)['"]\)/);
  if (roleMatch) {
    return `getBy${roleMatch[1]}('${roleMatch[2]}')`;
  }

  // Pattern: [data-testid="..."]
  const testIdMatch = errorMessage.match(/\[data-testid=["']([^"']+)["']\]/);
  if (testIdMatch) {
    return `[data-testid="${testIdMatch[1]}"]`;
  }

  // Pattern: #id or .class at word boundary
  const cssMatch = errorMessage.match(/(?:^|\s)([#.][a-zA-Z][\w-]*)/);
  if (cssMatch) {
    return cssMatch[1];
  }

  return undefined;
}

function extractMatchCount(errorMessage: string): number | undefined {
  // Pattern: "resolved to N elements"
  const match = errorMessage.match(/resolved to (\d+) elements/);
  if (match) {
    return parseInt(match[1], 10);
  }
  return undefined;
}

// ─────────────────────────────────────────────────────────────────────────────
// Remediation Engine
// ─────────────────────────────────────────────────────────────────────────────

function generateRemediation(
  category: FlakeCategory,
  selector: string | undefined,
  matchCount: number | undefined
): Remediation {
  switch (category) {
    case 'strict':
      return {
        suggestion: matchCount
          ? `Add :visible filter or use .first()/.nth() — ${matchCount} elements matched`
          : 'Add :visible filter or use .first() to narrow down multiple matches',
        confidence: 'high',
        autoFixable: true,
      };

    case 'timeout':
      return {
        suggestion: 'Increase waitFor timeout or verify element renders within expected time',
        confidence: 'medium',
        autoFixable: false,
      };

    case 'visibility':
      return {
        suggestion: 'Add explicit waitFor({ state: "visible" }) before interaction or check for overlays',
        confidence: 'high',
        autoFixable: true,
      };

    case 'detached':
      return {
        suggestion: 'Re-query the element after navigation/DOM update — element was removed during action',
        confidence: 'medium',
        autoFixable: false,
      };

    case 'selector_changed':
      return {
        suggestion: selector
          ? `Selector "${selector}" no longer matches — DOM may have changed. Run selector-repair.ts`
          : 'Element selector no longer matches DOM structure. Regenerate with CAF',
        confidence: 'high',
        autoFixable: true,
      };

    case 'element_relocated':
      return {
        suggestion: 'Element position changed — add scroll into view or wait for layout stability',
        confidence: 'medium',
        autoFixable: false,
      };

    case 'timing_race':
      return {
        suggestion: 'Element appeared after timeout — increase timeout or add explicit wait condition',
        confidence: 'medium',
        autoFixable: false,
      };

    case 'stale_reference':
      return {
        suggestion: 'Element reference became stale — re-locate element before interaction',
        confidence: 'high',
        autoFixable: false,
      };

    case 'network_dependency':
      return {
        suggestion: 'Use runWithNetwork() to wait for API response before proceeding',
        confidence: 'high',
        autoFixable: false,
      };

    default:
      return {
        suggestion: 'Manual investigation required — review test logs and trace',
        confidence: 'low',
        autoFixable: false,
      };
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// Trace File Parsing
// ─────────────────────────────────────────────────────────────────────────────

function findTraceFiles(): string[] {
  if (!fs.existsSync(TRACES_DIR)) {
    return [];
  }

  const files: string[] = [];

  function scanDir(dir: string) {
    const entries = fs.readdirSync(dir, { withFileTypes: true });

    for (const entry of entries) {
      const fullPath = path.join(dir, entry.name);

      if (entry.isDirectory()) {
        scanDir(fullPath);
      } else if (entry.name.endsWith('.zip')) {
        files.push(fullPath);
      }
    }
  }

  scanDir(TRACES_DIR);
  return files;
}

function parseTraceZip(zipPath: string): TraceEvent[] {
  // Playwright traces are zip files containing trace.trace (JSON lines) and resources
  //
  // LIMITATION: This is a basic zip parser that handles common cases but may fail on:
  // - ZIP files with data descriptors (general purpose bit flag)
  // - ZIP64 format (files > 4GB)
  // - Complex central directory structures
  //
  // For production use with diverse Playwright versions, consider using a dedicated
  // zip library like 'yauzl' which handles these edge cases reliably.
  // Example: npm install yauzl && import yauzl from 'yauzl';

  const events: TraceEvent[] = [];

  try {
    // Read zip file
    const zipBuffer = fs.readFileSync(zipPath);

    // Basic zip parsing - look for trace.trace file
    // Zip files have local file headers starting with PK\x03\x04
    let offset = 0;

    while (offset < zipBuffer.length - 30) {
      // Check for local file header signature
      if (
        zipBuffer[offset] === 0x50 &&
        zipBuffer[offset + 1] === 0x4b &&
        zipBuffer[offset + 2] === 0x03 &&
        zipBuffer[offset + 3] === 0x04
      ) {
        // Read header fields
        const compressionMethod = zipBuffer.readUInt16LE(offset + 8);
        const compressedSize = zipBuffer.readUInt32LE(offset + 18);
        const fileNameLength = zipBuffer.readUInt16LE(offset + 26);
        const extraFieldLength = zipBuffer.readUInt16LE(offset + 28);
        const fileName = zipBuffer.slice(offset + 30, offset + 30 + fileNameLength).toString('utf-8');

        const dataOffset = offset + 30 + fileNameLength + extraFieldLength;

        // We're interested in trace files
        if (fileName === 'trace.trace' || fileName.endsWith('.trace')) {
          const compressedData = zipBuffer.slice(dataOffset, dataOffset + compressedSize);

          let data: Buffer;
          if (compressionMethod === 0) {
            // Stored (no compression)
            data = compressedData;
          } else if (compressionMethod === 8) {
            // Deflate
            try {
              data = zlib.inflateRawSync(compressedData);
            } catch {
              // Skip if decompression fails
              offset = dataOffset + compressedSize;
              continue;
            }
          } else {
            // Unsupported compression
            offset = dataOffset + compressedSize;
            continue;
          }

          // Parse JSON lines
          const lines = data.toString('utf-8').split('\n').filter(Boolean);
          for (const line of lines) {
            try {
              const event = JSON.parse(line);
              events.push(event);
            } catch {
              // Skip invalid JSON
            }
          }
        }

        offset = dataOffset + compressedSize;
      } else {
        offset++;
      }
    }
  } catch {
    // Return empty events on error
  }

  return events;
}

function extractActionFromTrace(events: TraceEvent[]): ActionContext | undefined {
  // Look for the last action before an error
  let lastAction: ActionContext | undefined;

  for (const event of events) {
    if (event.type === 'action' || event.type === 'before') {
      const params = event.params || {};
      const selector = (params.selector as string) || (params.name as string) || '';

      lastAction = {
        action: (params.name as string) || event.type,
        targetSelector: selector,
        timestamp: event.timestamp || 0,
        duration: event.duration,
      };
    }

    if (event.error) {
      // Return the last action before the error
      return lastAction;
    }
  }

  return lastAction;
}

// ─────────────────────────────────────────────────────────────────────────────
// Test Results Processing
// ─────────────────────────────────────────────────────────────────────────────

function loadTestResults(): PlaywrightResults | null {
  if (!fs.existsSync(TEST_RESULTS_FILE)) {
    return null;
  }

  try {
    return JSON.parse(fs.readFileSync(TEST_RESULTS_FILE, 'utf-8'));
  } catch {
    return null;
  }
}

function extractFailures(results: PlaywrightResults): Array<{
  testName: string;
  testFile: string;
  errorMessage: string;
  errorStack?: string;
  tracePath?: string;
}> {
  const failures: Array<{
    testName: string;
    testFile: string;
    errorMessage: string;
    errorStack?: string;
    tracePath?: string;
  }> = [];

  function processSuite(suite: TestSuite, parentFile?: string) {
    const file = suite.file || parentFile || 'unknown';

    for (const test of suite.tests || []) {
      for (const result of test.results || []) {
        if (result.status === 'failed' || result.status === 'timedOut') {
          const tracePath = result.attachments?.find(a => a.name === 'trace')?.path;

          failures.push({
            testName: test.title,
            testFile: file,
            errorMessage: result.error?.message || 'Unknown error',
            errorStack: result.error?.stack,
            tracePath,
          });
        }
      }
    }

    for (const childSuite of suite.suites || []) {
      processSuite(childSuite, file);
    }
  }

  for (const suite of results.suites || []) {
    processSuite(suite);
  }

  return failures;
}

// ─────────────────────────────────────────────────────────────────────────────
// Lifecycle Integration
// ─────────────────────────────────────────────────────────────────────────────

function updateLifecycleForFlakes(failures: TriageResult[]): number {
  if (!fs.existsSync(LIFECYCLE_FILE)) {
    return 0;
  }

  let updated = 0;

  try {
    const store: LifecycleStore = JSON.parse(fs.readFileSync(LIFECYCLE_FILE, 'utf-8'));
    const timestamp = new Date().toISOString();

    for (const failure of failures) {
      if (!failure.selector) continue;

      const lifecycle = store.selectors[failure.selector];
      if (!lifecycle) continue;

      // Move to watch if currently active
      if (lifecycle.state === 'active') {
        lifecycle.state = 'watch';
        lifecycle.history.push({
          timestamp,
          action: `Moved to watch: flake detected (${failure.failureType})`,
        });
        updated++;
      }
    }

    if (updated > 0) {
      store.updatedAt = timestamp;
      fs.writeFileSync(LIFECYCLE_FILE, JSON.stringify(store, null, 2));
    }
  } catch {
    // Ignore errors
  }

  return updated;
}

// ─────────────────────────────────────────────────────────────────────────────
// Report Generation
// ─────────────────────────────────────────────────────────────────────────────

function generateReport(failures: TriageResult[]): FlakeTriageReport {
  const byCategory: Record<string, number> = {};
  let autoFixable = 0;
  let selectorIssues = 0;

  for (const failure of failures) {
    byCategory[failure.failureType] = (byCategory[failure.failureType] || 0) + 1;

    if (failure.remediation.autoFixable) {
      autoFixable++;
    }

    if (failure.selector) {
      selectorIssues++;
    }
  }

  return {
    version: '1.0',
    generatedAt: new Date().toISOString(),
    summary: {
      totalFailures: failures.length,
      byCategory,
      autoFixable,
      selectorIssues,
    },
    failures,
  };
}

function printConsoleReport(report: FlakeTriageReport): void {
  console.log('═══════════════════════════════════════════════════════════════');
  console.log('  T5.5: Flake Auto-Triage Report');
  console.log('═══════════════════════════════════════════════════════════════');

  console.log('\nSummary:');
  console.log(`  Total Failures:   ${report.summary.totalFailures}`);

  for (const [category, count] of Object.entries(report.summary.byCategory)) {
    const pct = Math.round((count / report.summary.totalFailures) * 100);
    console.log(`  ${category.padEnd(16)}: ${count} (${pct}%)`);
  }

  console.log(`  Auto-Fixable:     ${report.summary.autoFixable}`);
  console.log(`  Selector Issues:  ${report.summary.selectorIssues}`);

  if (report.failures.length > 0) {
    console.log('\n───────────────────────────────────────────────────────────────');
    console.log('Failures:');

    for (let i = 0; i < report.failures.length; i++) {
      const f = report.failures[i];
      console.log(`\n[${i + 1}] ${f.testFile}`);
      console.log(`    Test: ${f.testName}`);
      console.log(`    Type: ${f.failureType}`);

      if (f.selector) {
        console.log(`    Selector: ${f.selector}`);
        if (f.selectorMeta) {
          console.log(
            `    Score: ${f.selectorMeta.score} | Strategy: ${f.selectorMeta.strategy} | State: ${f.selectorMeta.lifecycleState}`
          );
        }
      }

      console.log(`\n    ▸ Root Cause: ${f.errorMessage.substring(0, 80)}${f.errorMessage.length > 80 ? '...' : ''}`);
      console.log(`    ▸ Suggestion: ${f.remediation.suggestion}`);
      console.log(
        `    ▸ Confidence: ${f.remediation.confidence.toUpperCase()} | Auto-Fix: ${f.remediation.autoFixable ? 'YES' : 'NO'}`
      );
    }
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// Main Entry Point
// ─────────────────────────────────────────────────────────────────────────────

function main() {
  const args = process.argv.slice(2);
  const integrate = args.includes('--integrate');
  const ciMode = args.includes('--ci');
  const jsonOutput = args.includes('--json');
  const specificFile = args.find(a => a.startsWith('--file='))?.split('=')[1];

  console.log('═══════════════════════════════════════════════════════════════');
  console.log('  T5.5: Full Flake Auto-Triage');
  console.log('═══════════════════════════════════════════════════════════════');

  // Load metadata
  const selectorMetadata = loadSelectorMetadata();
  const lifecycleStates = loadLifecycleState();

  console.log(`\nLoaded ${selectorMetadata.size} selector metadata entries.`);
  console.log(`Loaded ${lifecycleStates.size} lifecycle states.`);

  // Load test results
  const testResults = loadTestResults();
  if (!testResults) {
    console.log('\nNo test-results.json found. Run tests first.');

    if (ciMode) {
      process.exit(0);
    }
    return;
  }

  // Extract failures from test results
  const rawFailures = extractFailures(testResults);
  console.log(`\nFound ${rawFailures.length} test failures.`);

  if (rawFailures.length === 0) {
    console.log('No failures to triage.');

    if (ciMode) {
      process.exit(0);
    }
    return;
  }

  // Find trace files
  const traceFiles = specificFile ? [specificFile] : findTraceFiles();
  console.log(`Found ${traceFiles.length} trace files in ./${TRACES_DIR}/`);

  // Parse traces for additional context
  const traceContextMap = new Map<string, ActionContext>();
  for (const tracePath of traceFiles) {
    const events = parseTraceZip(tracePath);
    const actionContext = extractActionFromTrace(events);

    if (actionContext) {
      // Use trace filename as key
      const traceKey = path.basename(tracePath);
      traceContextMap.set(traceKey, actionContext);
    }
  }

  // Process failures
  const triageResults: TriageResult[] = [];

  for (const failure of rawFailures) {
    const category = classifyFlake(failure.errorMessage, failure.errorStack);
    const selector = extractSelector(failure.errorMessage);
    const matchCount = extractMatchCount(failure.errorMessage);

    // Get selector metadata
    let selectorMeta: SelectorMeta | undefined;
    if (selector) {
      const meta = selectorMetadata.get(selector);
      const state = lifecycleStates.get(selector);

      if (meta || state) {
        selectorMeta = {
          score: meta?.score || 0,
          strategy: meta?.strategy || 'unknown',
          lifecycleState: state || 'unknown',
        };
      }
    }

    // Get action context from trace
    let actionContext: ActionContext | undefined;
    if (failure.tracePath) {
      const traceKey = path.basename(failure.tracePath);
      actionContext = traceContextMap.get(traceKey);
    }

    // Build DOM context if we have match count
    let domContext: DomContext | undefined;
    if (matchCount !== undefined) {
      domContext = {
        elementExists: matchCount > 0,
        elementVisible: true, // Assume visible if matched
        matchCount,
      };
    }

    // Generate remediation
    const remediation = generateRemediation(category, selector, matchCount);

    triageResults.push({
      testName: failure.testName,
      testFile: failure.testFile,
      failureType: category,
      errorMessage: failure.errorMessage,
      selector,
      selectorMeta,
      actionContext,
      domContext,
      remediation,
    });
  }

  // Generate report
  const report = generateReport(triageResults);

  // Output report
  if (jsonOutput) {
    console.log(JSON.stringify(report, null, 2));
  } else {
    printConsoleReport(report);
  }

  // Save JSON report
  fs.writeFileSync(OUTPUT_FILE, JSON.stringify(report, null, 2));
  console.log(`\n✓ Report saved to ${OUTPUT_FILE}`);

  // Lifecycle integration
  if (integrate) {
    const updated = updateLifecycleForFlakes(triageResults);
    if (updated > 0) {
      console.log(`✓ Updated ${updated} selector(s) in lifecycle (moved to 'watch')`);
    }
  }

  // CI mode exit codes
  if (ciMode) {
    // Exit with error if critical issues found
    const criticalCount = triageResults.filter(
      r => r.failureType === 'selector_changed' || r.failureType === 'strict'
    ).length;

    if (criticalCount > 0) {
      console.log(`\n⚠ ${criticalCount} critical flake(s) detected.`);
      process.exit(1);
    }
  }

  console.log('\n═══════════════════════════════════════════════════════════════');
}

// Guard CLI entry point
if (require.main === module) {
  main();
}

// Exports for testing and integration
export {
  classifyFlake,
  extractSelector,
  generateRemediation,
  FlakeTriageReport,
  TriageResult,
  FlakeCategory,
};
