// Auto-generated by CAF
// T4.3: AI-Driven Locator Optimizer
// Analyzes selectors and provides optimization suggestions

import fs from 'fs';
import path from 'path';

// ─────────────────────────────────────────────────────────────────────────────
// Configuration
// ─────────────────────────────────────────────────────────────────────────────

const ANALYSIS_DIR = 'migration-analysis';
const OPTIMIZATION_REPORT_FILE = 'locator-optimization-report.json';

// ─────────────────────────────────────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────────────────────────────────────

type OptimizationType =
  | 'prefer-data-testid'
  | 'avoid-index'
  | 'simplify-chain'
  | 'use-role'
  | 'avoid-class-chain'
  | 'prefer-id'
  | 'text-stability'
  | 'accessibility';

interface OptimizationSuggestion {
  type: OptimizationType;
  priority: 'high' | 'medium' | 'low';
  suggestion: string;
  reasoning: string;
  example?: {
    before: string;
    after: string;
  };
}

interface SelectorAnalysis {
  selector: string;
  currentScore: number;
  potentialScore: number;
  suggestions: OptimizationSuggestion[];
  complexity: 'simple' | 'moderate' | 'complex';
  stability: 'stable' | 'fragile' | 'volatile';
}

interface OptimizationReport {
  timestamp: string;
  totalSelectors: number;
  analyzedSelectors: number;
  analyses: SelectorAnalysis[];
  summary: {
    byType: Record<OptimizationType, number>;
    byPriority: { high: number; medium: number; low: number };
    avgPotentialImprovement: number;
  };
}

interface SelectorCandidate {
  primary: string;
  fallback: string[];
  score: number;
  strategy: string;
}

interface AnalysisFile {
  pageName: string;
  domain: string;
  selectors: SelectorCandidate[];
}

// ─────────────────────────────────────────────────────────────────────────────
// Selector Pattern Analysis
// ─────────────────────────────────────────────────────────────────────────────

const PATTERNS = {
  dataTestId: /\[data-testid[=~^$*|]?="[^"]+"\]/,
  id: /#[\w-]+/,
  role: /\[role="[^"]+"\]/,
  nthChild: /:nth-child\(\d+\)/,
  nthOfType: /:nth-of-type\(\d+\)/,
  classChain: /\.[\w-]+\.[\w-]+\.[\w-]+/,  // 3+ chained classes
  deepNesting: /\s>\s.*\s>\s.*\s>\s/,      // 3+ levels of '>'
  textContent: /:has-text\([^)]+\)|:text\([^)]+\)/,
  ariaLabel: /\[aria-label[=~^$*|]?="[^"]+"\]/,
  placeholder: /\[placeholder[=~^$*|]?="[^"]+"\]/,
  fragileClass: /\.(w-\d+|h-\d+|p-\d+|m-\d+|bg-|text-|flex|grid)/,  // Tailwind utility classes
};

function analyzeComplexity(selector: string): 'simple' | 'moderate' | 'complex' {
  const parts = selector.split(/[\s>+~]/).filter(Boolean);
  const nestedLevel = (selector.match(/\s>\s/g) || []).length;

  if (parts.length <= 2 && nestedLevel <= 1) {
    return 'simple';
  }
  if (parts.length <= 4 && nestedLevel <= 2) {
    return 'moderate';
  }
  return 'complex';
}

function analyzeStability(selector: string, score: number): 'stable' | 'fragile' | 'volatile' {
  // High score + good patterns = stable
  if (score >= 90 && (PATTERNS.dataTestId.test(selector) || PATTERNS.id.test(selector))) {
    return 'stable';
  }

  // Low score or fragile patterns = volatile
  if (score < 60 || PATTERNS.fragileClass.test(selector)) {
    return 'volatile';
  }

  // Middle ground
  if (
    PATTERNS.nthChild.test(selector) ||
    PATTERNS.nthOfType.test(selector) ||
    PATTERNS.classChain.test(selector)
  ) {
    return 'fragile';
  }

  return score >= 75 ? 'stable' : 'fragile';
}

// ─────────────────────────────────────────────────────────────────────────────
// Optimization Engine
// ─────────────────────────────────────────────────────────────────────────────

function generateSuggestions(selector: string, score: number): OptimizationSuggestion[] {
  const suggestions: OptimizationSuggestion[] = [];

  // Rule 1: No data-testid → suggest adding one
  if (!PATTERNS.dataTestId.test(selector)) {
    suggestions.push({
      type: 'prefer-data-testid',
      priority: 'high',
      suggestion: 'Add data-testid attribute to the element',
      reasoning: 'data-testid provides stable, test-specific targeting unaffected by styling or structure changes',
      example: {
        before: selector.substring(0, 40),
        after: '[data-testid="descriptive-name"]',
      },
    });
  }

  // Rule 2: Index-based selectors
  if (PATTERNS.nthChild.test(selector) || PATTERNS.nthOfType.test(selector)) {
    suggestions.push({
      type: 'avoid-index',
      priority: 'high',
      suggestion: 'Replace index-based selector with unique attribute',
      reasoning: 'Index selectors break when elements are added/removed from the DOM',
      example: {
        before: selector.match(/:nth-(?:child|of-type)\(\d+\)/)?.[0] || ':nth-child(2)',
        after: '[data-index="specific-id"]',
      },
    });
  }

  // Rule 3: Deep nesting
  if (PATTERNS.deepNesting.test(selector)) {
    suggestions.push({
      type: 'simplify-chain',
      priority: 'medium',
      suggestion: 'Simplify selector chain by targeting a closer unique ancestor',
      reasoning: 'Deep nesting increases fragility and maintenance burden',
    });
  }

  // Rule 4: No role attribute for interactive elements
  if (
    (selector.includes('button') || selector.includes('input') || selector.includes('link')) &&
    !PATTERNS.role.test(selector)
  ) {
    suggestions.push({
      type: 'use-role',
      priority: 'medium',
      suggestion: 'Consider using role attribute for accessibility-based selection',
      reasoning: 'Role selectors align with accessibility standards and are semantically stable',
      example: {
        before: selector.substring(0, 30),
        after: '[role="button"]',
      },
    });
  }

  // Rule 5: Multiple chained classes
  if (PATTERNS.classChain.test(selector)) {
    suggestions.push({
      type: 'avoid-class-chain',
      priority: 'medium',
      suggestion: 'Reduce class chain dependency',
      reasoning: 'Multiple class selectors are often styling-dependent and change with CSS updates',
    });
  }

  // Rule 6: Tailwind/utility class usage
  if (PATTERNS.fragileClass.test(selector)) {
    suggestions.push({
      type: 'avoid-class-chain',
      priority: 'high',
      suggestion: 'Remove utility class dependencies (Tailwind, Bootstrap)',
      reasoning: 'Utility classes change frequently during design iterations',
    });
  }

  // Rule 7: Has stable ID but not using it optimally
  if (PATTERNS.id.test(selector) && selector.length > 30) {
    suggestions.push({
      type: 'prefer-id',
      priority: 'low',
      suggestion: 'Simplify to use just the ID selector',
      reasoning: 'ID selectors are unique and don\'t need additional qualifiers',
    });
  }

  // Rule 8: Text-based selectors
  if (PATTERNS.textContent.test(selector)) {
    suggestions.push({
      type: 'text-stability',
      priority: 'medium',
      suggestion: 'Consider adding attribute selector as fallback to text',
      reasoning: 'Text content may change with localization or copy updates',
    });
  }

  // Rule 9: Has aria-label → good, but could add data-testid for tests
  if (PATTERNS.ariaLabel.test(selector) && !PATTERNS.dataTestId.test(selector)) {
    suggestions.push({
      type: 'accessibility',
      priority: 'low',
      suggestion: 'Add data-testid alongside aria-label for test stability',
      reasoning: 'aria-label is for accessibility; data-testid is purpose-built for testing',
    });
  }

  return suggestions;
}

function calculatePotentialScore(currentScore: number, suggestions: OptimizationSuggestion[]): number {
  let improvement = 0;

  for (const suggestion of suggestions) {
    switch (suggestion.priority) {
      case 'high':
        improvement += 10;
        break;
      case 'medium':
        improvement += 5;
        break;
      case 'low':
        improvement += 2;
        break;
    }
  }

  // Cap at 100
  return Math.min(100, currentScore + improvement);
}

function analyzeSelector(selector: string, score: number): SelectorAnalysis {
  const suggestions = generateSuggestions(selector, score);
  const potentialScore = calculatePotentialScore(score, suggestions);

  return {
    selector,
    currentScore: score,
    potentialScore,
    suggestions,
    complexity: analyzeComplexity(selector),
    stability: analyzeStability(selector, score),
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// Report Generation
// ─────────────────────────────────────────────────────────────────────────────

function findAnalysisFiles(dir: string): string[] {
  const files: string[] = [];

  if (!fs.existsSync(dir)) {
    return files;
  }

  const entries = fs.readdirSync(dir, { withFileTypes: true });

  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);

    if (entry.isDirectory()) {
      files.push(...findAnalysisFiles(fullPath));
    } else if (entry.name.endsWith('.analysis.json')) {
      files.push(fullPath);
    }
  }

  return files;
}

function collectSelectors(): SelectorCandidate[] {
  const analysisFiles = findAnalysisFiles(ANALYSIS_DIR);
  const selectors: SelectorCandidate[] = [];

  for (const file of analysisFiles) {
    try {
      const content = fs.readFileSync(file, 'utf-8');
      const analysis: AnalysisFile = JSON.parse(content);

      for (const selector of analysis.selectors) {
        selectors.push(selector);
      }
    } catch {
      // Skip invalid files
    }
  }

  return selectors;
}

function generateOptimizationReport(): OptimizationReport {
  const selectors = collectSelectors();
  const analyses: SelectorAnalysis[] = [];

  const byType: Record<OptimizationType, number> = {
    'prefer-data-testid': 0,
    'avoid-index': 0,
    'simplify-chain': 0,
    'use-role': 0,
    'avoid-class-chain': 0,
    'prefer-id': 0,
    'text-stability': 0,
    'accessibility': 0,
  };

  const byPriority = { high: 0, medium: 0, low: 0 };
  let totalImprovement = 0;

  for (const selector of selectors) {
    const analysis = analyzeSelector(selector.primary, selector.score);
    analyses.push(analysis);

    // Aggregate stats
    for (const suggestion of analysis.suggestions) {
      byType[suggestion.type]++;
      byPriority[suggestion.priority]++;
    }

    totalImprovement += analysis.potentialScore - analysis.currentScore;
  }

  // Sort by potential improvement descending
  analyses.sort((a, b) =>
    (b.potentialScore - b.currentScore) - (a.potentialScore - a.currentScore)
  );

  return {
    timestamp: new Date().toISOString(),
    totalSelectors: selectors.length,
    analyzedSelectors: analyses.length,
    analyses,
    summary: {
      byType,
      byPriority,
      avgPotentialImprovement: analyses.length > 0
        ? Math.round((totalImprovement / analyses.length) * 100) / 100
        : 0,
    },
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// CLI Entry Point
// ─────────────────────────────────────────────────────────────────────────────

function main() {
  const args = process.argv.slice(2);

  const verbose = args.includes('--verbose');
  const ciMode = args.includes('--ci');
  const maxDisplay = verbose ? 50 : 10;

  console.log('═══════════════════════════════════════════════════════════════');
  console.log('  T4.3: AI-Driven Locator Optimizer');
  console.log('═══════════════════════════════════════════════════════════════');

  const report = generateOptimizationReport();

  if (report.analyzedSelectors === 0) {
    console.log('\n⚠ No selectors found in analysis files.');
    console.log('  Run: npm run caf -- analyze <url> first');
    process.exit(ciMode ? 0 : 1);
  }

  console.log(`\nAnalyzed ${report.analyzedSelectors} selectors.`);

  // Top optimization opportunities
  const needsWork = report.analyses.filter(a => a.suggestions.length > 0);

  if (needsWork.length === 0) {
    console.log('\n✓ All selectors are optimally configured!');
  } else {
    console.log(`\nOptimization Opportunities (${needsWork.length} selectors):`);
    console.log('┌──────────────────────────────────────────────────────────────┐');
    console.log('│ Selector                     │ Score │ Potential │ Priority │');
    console.log('├──────────────────────────────────────────────────────────────┤');

    for (let i = 0; i < Math.min(needsWork.length, maxDisplay); i++) {
      const a = needsWork[i];
      const selDisplay = a.selector.substring(0, 28).padEnd(28);
      const scoreDisplay = `${a.currentScore}`.padStart(5);
      const potentialDisplay = `${a.potentialScore}`.padStart(9);
      const topPriority = a.suggestions[0]?.priority || 'low';
      const prioDisplay = topPriority.toUpperCase().padEnd(8);
      console.log(`│ ${selDisplay} │ ${scoreDisplay} │ ${potentialDisplay} │ ${prioDisplay} │`);
    }

    if (needsWork.length > maxDisplay) {
      console.log(`│ ... and ${needsWork.length - maxDisplay} more (use --verbose)`);
    }

    console.log('└──────────────────────────────────────────────────────────────┘');
  }

  // Verbose: Show detailed suggestions
  if (verbose && needsWork.length > 0) {
    console.log('\n───────────────────────────────────────────────────────────────');
    console.log('Detailed Suggestions:');

    for (const a of needsWork.slice(0, 5)) {
      console.log(`\n${a.selector}:`);
      console.log(`  Complexity: ${a.complexity} | Stability: ${a.stability}`);

      for (const s of a.suggestions) {
        console.log(`  [${s.priority.toUpperCase()}] ${s.type}`);
        console.log(`    ${s.suggestion}`);
        console.log(`    Reason: ${s.reasoning}`);

        if (s.example) {
          console.log(`    Example: ${s.example.before} → ${s.example.after}`);
        }
      }
    }
  }

  // Summary by type
  console.log('\nSuggestion Types:');

  for (const [type, count] of Object.entries(report.summary.byType)) {
    if (count > 0) {
      console.log(`  ${type.padEnd(20)} ${count}`);
    }
  }

  console.log(`\nPriority Breakdown:`);
  console.log(`  High:   ${report.summary.byPriority.high}`);
  console.log(`  Medium: ${report.summary.byPriority.medium}`);
  console.log(`  Low:    ${report.summary.byPriority.low}`);
  console.log(`\nAvg Potential Improvement: +${report.summary.avgPotentialImprovement} points`);

  // Save report
  fs.writeFileSync(OPTIMIZATION_REPORT_FILE, JSON.stringify(report, null, 2));
  console.log(`\nReport saved to ${OPTIMIZATION_REPORT_FILE}`);

  // CI mode
  if (ciMode && report.summary.byPriority.high > 5) {
    console.log('\n⚠ OPTIMIZATION CHECK: WARNING (>5 high-priority issues)');
  }

  console.log('\n✓ LOCATOR OPTIMIZATION: COMPLETE');
}

// Guard CLI entry point
if (require.main === module) {
  main();
}

// Export for use in other modules
export { analyzeSelector, generateOptimizationReport, SelectorAnalysis, OptimizationReport };
