// Auto-generated by CAF
// T5.4: Migration Orchestration Engine
// Orchestrates end-to-end selector migration with rollback support

import fs from 'fs';
import path from 'path';
import { execSync } from 'child_process';

// ─────────────────────────────────────────────────────────────────────────────
// Configuration
// ─────────────────────────────────────────────────────────────────────────────

const ANALYSIS_DIR = 'migration-analysis';
const MIGRATION_STATE_FILE = '.caf-migration-state.json';
const MIGRATION_LOG_FILE = 'migration-log.json';

// ─────────────────────────────────────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────────────────────────────────────

type MigrationPhase = 'init' | 'analyze' | 'preview' | 'apply' | 'verify' | 'complete' | 'rollback';

interface MigrationStep {
  id: string;
  phase: MigrationPhase;
  status: 'pending' | 'running' | 'success' | 'failed' | 'skipped';
  timestamp?: string;
  duration?: number;
  error?: string;
  details?: string;
}

interface MigrationState {
  version: string;
  startedAt: string;
  lastUpdatedAt: string;
  currentPhase: MigrationPhase;
  steps: MigrationStep[];
  selectors: {
    total: number;
    migrated: number;
    failed: number;
    skipped: number;
  };
  rollbackAvailable: boolean;
  backupPath?: string;
}

interface MigrationPlan {
  analysisFiles: string[];
  selectorsToMigrate: number;
  estimatedDuration: string;
  riskLevel: 'low' | 'medium' | 'high';
  phases: Array<{
    name: string;
    description: string;
    command: string;
  }>;
}

// ─────────────────────────────────────────────────────────────────────────────
// State Management
// ─────────────────────────────────────────────────────────────────────────────

function loadState(): MigrationState | null {
  if (!fs.existsSync(MIGRATION_STATE_FILE)) {
    return null;
  }

  try {
    return JSON.parse(fs.readFileSync(MIGRATION_STATE_FILE, 'utf-8'));
  } catch {
    return null;
  }
}

function saveState(state: MigrationState): void {
  state.lastUpdatedAt = new Date().toISOString();
  fs.writeFileSync(MIGRATION_STATE_FILE, JSON.stringify(state, null, 2));
}

function initState(): MigrationState {
  const state: MigrationState = {
    version: '1.0',
    startedAt: new Date().toISOString(),
    lastUpdatedAt: new Date().toISOString(),
    currentPhase: 'init',
    steps: [],
    selectors: {
      total: 0,
      migrated: 0,
      failed: 0,
      skipped: 0,
    },
    rollbackAvailable: false,
  };

  saveState(state);
  return state;
}

function addStep(state: MigrationState, step: MigrationStep): void {
  step.timestamp = new Date().toISOString();
  state.steps.push(step);
  saveState(state);
}

function updateStep(state: MigrationState, stepId: string, updates: Partial<MigrationStep>): void {
  const step = state.steps.find(s => s.id === stepId);
  if (step) {
    Object.assign(step, updates);
    saveState(state);
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// Analysis Discovery
// ─────────────────────────────────────────────────────────────────────────────

function findAnalysisFiles(): string[] {
  const files: string[] = [];

  if (!fs.existsSync(ANALYSIS_DIR)) {
    return files;
  }

  function scanDir(dir: string) {
    const entries = fs.readdirSync(dir, { withFileTypes: true });

    for (const entry of entries) {
      const fullPath = path.join(dir, entry.name);

      if (entry.isDirectory()) {
        scanDir(fullPath);
      } else if (entry.name.endsWith('.analysis.json')) {
        files.push(fullPath);
      }
    }
  }

  scanDir(ANALYSIS_DIR);
  return files;
}

function countSelectors(analysisFiles: string[]): number {
  let total = 0;

  for (const file of analysisFiles) {
    try {
      const content = JSON.parse(fs.readFileSync(file, 'utf-8'));
      total += (content.selectors || []).length;
    } catch {
      // Skip invalid files
    }
  }

  return total;
}

// ─────────────────────────────────────────────────────────────────────────────
// Migration Phases
// ─────────────────────────────────────────────────────────────────────────────

function runPhase(phase: MigrationPhase, state: MigrationState): boolean {
  const stepId = phase + '-' + Date.now();

  addStep(state, {
    id: stepId,
    phase,
    status: 'running',
  });

  const startTime = Date.now();

  try {
    switch (phase) {
      case 'init':
        return executeInit(state, stepId);

      case 'analyze':
        return executeAnalyze(state, stepId);

      case 'preview':
        return executePreview(state, stepId);

      case 'apply':
        return executeApply(state, stepId);

      case 'verify':
        return executeVerify(state, stepId);

      case 'complete':
        return executeComplete(state, stepId);

      case 'rollback':
        return executeRollback(state, stepId);

      default:
        updateStep(state, stepId, { status: 'failed', error: 'Unknown phase' });
        return false;
    }
  } catch (error) {
    const errorMsg = error instanceof Error ? error.message : String(error);
    updateStep(state, stepId, {
      status: 'failed',
      error: errorMsg,
      duration: Date.now() - startTime,
    });
    return false;
  }
}

function executeInit(state: MigrationState, stepId: string): boolean {
  console.log('  Initializing migration...');

  // Create backup using cross-platform Node.js API
  const backupDir = '.caf-migration-backup-' + Date.now();
  if (fs.existsSync(ANALYSIS_DIR)) {
    fs.cpSync(ANALYSIS_DIR, backupDir, { recursive: true });
    state.backupPath = backupDir;
    state.rollbackAvailable = true;
  }

  // Find analysis files
  const analysisFiles = findAnalysisFiles();
  const selectorCount = countSelectors(analysisFiles);

  state.selectors.total = selectorCount;
  state.currentPhase = 'analyze';

  updateStep(state, stepId, {
    status: 'success',
    details: 'Found ' + analysisFiles.length + ' analysis files with ' + selectorCount + ' selectors',
  });

  return true;
}

function executeAnalyze(state: MigrationState, stepId: string): boolean {
  console.log('  Running analysis tools...');

  // Run CAF analysis scripts
  const commands = [
    { name: 'Lifecycle check', cmd: 'npm run ci:lifecycle 2>/dev/null || true' },
    { name: 'Fallback check', cmd: 'npm run ci:fallback-check 2>/dev/null || true' },
    { name: 'Score demotion', cmd: 'npm run ci:score-demotion -- --dry-run 2>/dev/null || true' },
  ];

  for (const { name, cmd } of commands) {
    console.log('    Running ' + name + '...');
    try {
      execSync(cmd, { encoding: 'utf-8', stdio: 'pipe' });
    } catch {
      // Continue even if individual commands fail
    }
  }

  state.currentPhase = 'preview';
  updateStep(state, stepId, { status: 'success', details: 'Analysis complete' });
  return true;
}

function executePreview(state: MigrationState, stepId: string): boolean {
  console.log('  Generating migration preview...');

  // Run repair pipeline in dry-run mode
  try {
    execSync('npm run repair:pipeline -- --dry-run 2>/dev/null || true', {
      encoding: 'utf-8',
      stdio: 'pipe',
    });
  } catch {
    // Continue
  }

  // Run DOM drift predictor
  try {
    execSync('npm run check:dom-drift 2>/dev/null || true', {
      encoding: 'utf-8',
      stdio: 'pipe',
    });
  } catch {
    // Continue
  }

  state.currentPhase = 'apply';
  updateStep(state, stepId, { status: 'success', details: 'Preview generated' });
  return true;
}

function executeApply(state: MigrationState, stepId: string): boolean {
  console.log('  Applying migrations...');

  // Run repair pipeline
  try {
    const output = execSync('npm run repair:pipeline 2>&1 || true', {
      encoding: 'utf-8',
      stdio: 'pipe',
    });

    // Parse output for migration counts
    const appliedMatch = output.match(/Applied:\s*(\d+)/);
    if (appliedMatch) {
      state.selectors.migrated = parseInt(appliedMatch[1], 10);
    }
  } catch {
    // Continue
  }

  // Run score demotion
  try {
    execSync('npm run ci:score-demotion 2>/dev/null || true', {
      encoding: 'utf-8',
      stdio: 'pipe',
    });
  } catch {
    // Continue
  }

  state.currentPhase = 'verify';
  updateStep(state, stepId, {
    status: 'success',
    details: 'Applied ' + state.selectors.migrated + ' migrations',
  });
  return true;
}

function executeVerify(state: MigrationState, stepId: string): boolean {
  console.log('  Verifying migrations...');

  // Run TypeScript check
  try {
    execSync('npx tsc --noEmit 2>&1', { encoding: 'utf-8', stdio: 'pipe' });
    console.log('    TypeScript check: PASS');
  } catch (error) {
    console.log('    TypeScript check: FAIL');
    updateStep(state, stepId, { status: 'failed', error: 'TypeScript validation failed' });
    return false;
  }

  // Generate release confidence
  try {
    execSync('npm run release-confidence 2>/dev/null || true', {
      encoding: 'utf-8',
      stdio: 'pipe',
    });
    console.log('    Release confidence: Generated');
  } catch {
    // Continue
  }

  state.currentPhase = 'complete';
  updateStep(state, stepId, { status: 'success', details: 'Verification passed' });
  return true;
}

function executeComplete(state: MigrationState, stepId: string): boolean {
  console.log('  Completing migration...');

  // Write migration log
  const log = {
    version: '1.0',
    completedAt: new Date().toISOString(),
    duration: Date.now() - new Date(state.startedAt).getTime(),
    selectors: state.selectors,
    steps: state.steps,
  };

  fs.writeFileSync(MIGRATION_LOG_FILE, JSON.stringify(log, null, 2));

  state.currentPhase = 'complete';
  updateStep(state, stepId, { status: 'success', details: 'Migration complete' });
  return true;
}

function executeRollback(state: MigrationState, stepId: string): boolean {
  console.log('  Rolling back migration...');

  if (!state.backupPath || !fs.existsSync(state.backupPath)) {
    updateStep(state, stepId, { status: 'failed', error: 'No backup available' });
    return false;
  }

  // Restore backup using cross-platform Node.js APIs
  try {
    // Remove current analysis directory
    if (fs.existsSync(ANALYSIS_DIR)) {
      fs.rmSync(ANALYSIS_DIR, { recursive: true, force: true });
    }
    // Restore from backup
    fs.renameSync(state.backupPath, ANALYSIS_DIR);
  } catch (error) {
    updateStep(state, stepId, {
      status: 'failed',
      error: 'Rollback failed: ' + (error instanceof Error ? error.message : String(error)),
    });
    return false;
  }

  state.rollbackAvailable = false;
  state.currentPhase = 'init';
  updateStep(state, stepId, { status: 'success', details: 'Rollback complete' });
  return true;
}

// ─────────────────────────────────────────────────────────────────────────────
// Plan Generation
// ─────────────────────────────────────────────────────────────────────────────

function generatePlan(): MigrationPlan {
  const analysisFiles = findAnalysisFiles();
  const selectorCount = countSelectors(analysisFiles);

  let riskLevel: 'low' | 'medium' | 'high' = 'low';
  if (selectorCount > 100) riskLevel = 'high';
  else if (selectorCount > 50) riskLevel = 'medium';

  const estimatedMinutes = Math.ceil(selectorCount / 10) + 5;

  return {
    analysisFiles,
    selectorsToMigrate: selectorCount,
    estimatedDuration: estimatedMinutes + ' minutes',
    riskLevel,
    phases: [
      { name: 'init', description: 'Create backup and discover selectors', command: 'npm run migrate:run -- --phase init' },
      { name: 'analyze', description: 'Run analysis tools', command: 'npm run migrate:run -- --phase analyze' },
      { name: 'preview', description: 'Generate migration preview', command: 'npm run migrate:run -- --phase preview' },
      { name: 'apply', description: 'Apply migrations', command: 'npm run migrate:run -- --phase apply' },
      { name: 'verify', description: 'Verify changes', command: 'npm run migrate:run -- --phase verify' },
      { name: 'complete', description: 'Complete migration', command: 'npm run migrate:run -- --phase complete' },
    ],
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// Console Output
// ─────────────────────────────────────────────────────────────────────────────

function printPlan(plan: MigrationPlan): void {
  console.log('═══════════════════════════════════════════════════════════════');
  console.log('  T5.4: Migration Orchestration Engine — Plan');
  console.log('═══════════════════════════════════════════════════════════════');

  console.log('\nMigration Summary:');
  console.log('  Analysis Files: ' + plan.analysisFiles.length);
  console.log('  Selectors: ' + plan.selectorsToMigrate);
  console.log('  Estimated Duration: ' + plan.estimatedDuration);
  console.log('  Risk Level: ' + plan.riskLevel.toUpperCase());

  console.log('\nPhases:');
  for (let i = 0; i < plan.phases.length; i++) {
    const phase = plan.phases[i];
    console.log('  ' + (i + 1) + '. ' + phase.name + ' — ' + phase.description);
  }

  console.log('\nTo start migration:');
  console.log('  npm run migrate:run');
  console.log('\nTo run specific phase:');
  console.log('  npm run migrate:run -- --phase <phase-name>');
  console.log('\nTo rollback:');
  console.log('  npm run migrate:run -- --rollback');
}

function printStatus(state: MigrationState): void {
  console.log('═══════════════════════════════════════════════════════════════');
  console.log('  T5.4: Migration Orchestration Engine — Status');
  console.log('═══════════════════════════════════════════════════════════════');

  console.log('\nCurrent Phase: ' + state.currentPhase);
  console.log('Started: ' + state.startedAt);
  console.log('Last Updated: ' + state.lastUpdatedAt);

  console.log('\nSelectors:');
  console.log('  Total: ' + state.selectors.total);
  console.log('  Migrated: ' + state.selectors.migrated);
  console.log('  Failed: ' + state.selectors.failed);
  console.log('  Skipped: ' + state.selectors.skipped);

  console.log('\nRollback Available: ' + (state.rollbackAvailable ? 'Yes' : 'No'));

  if (state.steps.length > 0) {
    console.log('\nRecent Steps:');
    for (const step of state.steps.slice(-5)) {
      const icon = step.status === 'success' ? '✓' :
        step.status === 'failed' ? '✗' :
        step.status === 'running' ? '...' : '○';
      console.log('  ' + icon + ' ' + step.phase + ' (' + step.status + ')');
      if (step.details) console.log('    ' + step.details);
      if (step.error) console.log('    Error: ' + step.error);
    }
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// CLI Entry Point
// ─────────────────────────────────────────────────────────────────────────────

function main() {
  const args = process.argv.slice(2);
  const showPlan = args.includes('--plan');
  const showStatus = args.includes('--status');
  const rollback = args.includes('--rollback');
  const phaseArg = args.find(a => a.startsWith('--phase='));
  const specificPhase = phaseArg ? phaseArg.split('=')[1] as MigrationPhase : null;

  console.log('═══════════════════════════════════════════════════════════════');
  console.log('  T5.4: Migration Orchestration Engine');
  console.log('═══════════════════════════════════════════════════════════════');

  // Show plan
  if (showPlan) {
    const plan = generatePlan();
    printPlan(plan);
    return;
  }

  // Load or init state
  let state = loadState();

  // Show status
  if (showStatus) {
    if (state) {
      printStatus(state);
    } else {
      console.log('\nNo migration in progress.');
    }
    return;
  }

  // Rollback
  if (rollback) {
    if (!state) {
      console.log('\nNo migration to rollback.');
      return;
    }
    if (!state.rollbackAvailable) {
      console.log('\nNo backup available for rollback.');
      return;
    }
    console.log('\nStarting rollback...');
    runPhase('rollback', state);
    console.log('\n✓ Rollback complete.');
    return;
  }

  // Run specific phase
  if (specificPhase) {
    if (!state) {
      state = initState();
    }
    console.log('\nRunning phase: ' + specificPhase);
    const success = runPhase(specificPhase, state);
    console.log(success ? '\n✓ Phase complete.' : '\n✗ Phase failed.');
    return;
  }

  // Run full migration
  if (!state || state.currentPhase === 'complete') {
    state = initState();
  }

  console.log('\nStarting migration orchestration...\n');

  const phases: MigrationPhase[] = ['init', 'analyze', 'preview', 'apply', 'verify', 'complete'];
  const startIndex = phases.indexOf(state.currentPhase);

  for (let i = startIndex; i < phases.length; i++) {
    const phase = phases[i];
    console.log('Phase ' + (i + 1) + '/' + phases.length + ': ' + phase);

    const success = runPhase(phase, state);

    if (!success) {
      console.log('\n✗ Migration failed at phase: ' + phase);
      console.log('  Run with --rollback to restore backup.');
      process.exit(1);
    }

    console.log('');
  }

  console.log('═══════════════════════════════════════════════════════════════');
  console.log('  Migration Complete!');
  console.log('═══════════════════════════════════════════════════════════════');
  console.log('\nSelectors migrated: ' + state.selectors.migrated);
  console.log('Log saved to: ' + MIGRATION_LOG_FILE);
}

// Guard CLI entry point
if (require.main === module) {
  main();
}

// Exports for testing
export { generatePlan, MigrationState, MigrationPlan };
