// CAF Test Skeleton Generator
// Creates a full CAF flow scaffold: spec, actions, fixture, assertions, page, component.
//
// Usage:
//   npm run new-flow -- <module> <FlowName>                        (empty stubs)
//   npm run new-flow -- <module> <FlowName> --analysis <path.json> (analysis-driven)

import fs from 'fs';
import path from 'path';
import { toPascalCase, toCamelCase, sanitize } from './naming';

interface Segment {
  id: string;
  type: string;
  selectorHint: string;
  semanticName?: string;
}

interface Analysis {
  pageName: string;
  domain: string;
  segments: Segment[];
}

const rawArgs = process.argv.slice(2);
const flagIdx = rawArgs.indexOf('--analysis');
const analysisPath = flagIdx !== -1 ? rawArgs[flagIdx + 1] : null;

if (flagIdx !== -1 && (!analysisPath || analysisPath.startsWith('--'))) {
  console.error('Error: --analysis requires a path to an analysis.json file.');
  console.error('Usage: npm run new-flow -- <module> <FlowName> --analysis <path.json>');
  process.exit(1);
}

const positionalArgs = flagIdx !== -1
  ? rawArgs.filter((_, i) => i !== flagIdx && i !== flagIdx + 1)
  : rawArgs;

const [moduleName, flow] = positionalArgs;
if (!moduleName || !flow) {
  console.error('Usage: npm run new-flow -- <module> <FlowName> [--analysis <path.json>]');
  process.exit(1);
}

const camelCase = toCamelCase(flow);
const kebabCase = flow.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();

const paths = {
  component: `src/components/${moduleName}/${flow}.component.ts`,
  page: `src/pages/${moduleName}/${flow}Page.page.ts`,
  actions: `src/actions/${moduleName}/${flow}.actions.ts`,
  assertions: `src/assertions/${moduleName}/${flow}.assertions.ts`,
  fixture: `src/fixtures/${camelCase}.fixture.ts`,
  spec: `tests/${moduleName}/${kebabCase}.spec.ts`,
};

Object.values(paths).forEach(p => fs.mkdirSync(path.dirname(p), { recursive: true }));

function writeIfNew(filePath: string, content: string) {
  if (fs.existsSync(filePath)) {
    console.log(`Skipping existing: ${filePath}`);
    return;
  }
  fs.writeFileSync(filePath, content);
  console.log(`Created: ${filePath}`);
}

if (analysisPath) {
  if (!fs.existsSync(analysisPath)) {
    console.error(`Analysis file not found: ${analysisPath}`);
    process.exit(1);
  }

  const analysis: Analysis = JSON.parse(fs.readFileSync(analysisPath, 'utf-8'));
  const pageName = analysis.pageName;
  const pageParam = toCamelCase(pageName);

  const sortedSegments = [...analysis.segments].sort((a, b) => {
    const nameA = a.semanticName || a.id;
    const nameB = b.semanticName || b.id;
    return nameA.localeCompare(nameB);
  });

  const segmentNames = sortedSegments.map(s =>
    s.semanticName ? sanitize(s.semanticName) : toPascalCase(s.id)
  );

  const testSteps = segmentNames.map(name =>
    `    await test.step('Verify ${name}', async () => {\n` +
    `      await ${flow}.assertions.verify${name}Visible();\n` +
    `    });`
  ).join('\n\n');

  writeIfNew(paths.spec, `// Auto-generated by CAF — analysis-driven test skeleton.
import { test } from '@/fixtures/${camelCase}.fixture';

test('${flow} — full flow', async ({ ${flow} }) => {
  await test.step('Execute flow', async () => {
    await ${flow}.run();
  });

${testSteps}
});
`);

  writeIfNew(paths.actions, `// Auto-generated by CAF — extend with business flow methods.
import { BaseAction } from '@/core/base/BaseAction';
import { ${pageName}Page } from '@/pages/${analysis.domain}/${pageName}.page';

export class ${flow}Actions extends BaseAction {

  constructor(private readonly ${pageParam}: ${pageName}Page) {
    super();
    this.setPage(${pageParam}.getPage);
  }

  async run(): Promise<void> {
    // TODO: Implement flow steps (5-15 lines each).
  }

}
`);

  const assertionMethods = segmentNames.map(name => {
    const propName = toCamelCase(name);
    return (
      `  async verify${name}Visible(): Promise<void> {\n` +
      `    await this.${pageParam}.components.${propName}.waitForVisible();\n` +
      `  }`
    );
  }).join('\n\n');

  writeIfNew(paths.assertions, `// Auto-generated by CAF — extend with verification methods.
import { ${pageName}Page } from '@/pages/${analysis.domain}/${pageName}.page';

export class ${flow}Assertions {

  constructor(private readonly ${pageParam}: ${pageName}Page) {}

${assertionMethods}

}
`);

  writeIfNew(paths.fixture, `// Auto-generated by CAF — fixture wires page → actions → assertions.
import { test as base } from '@playwright/test';
import { ThirdPartyBlocker } from '@/core/sync/ThirdPartyBlocker';
import { ${pageName}Page } from '@/pages/${analysis.domain}/${pageName}.page';
import { ${flow}Actions } from '@/actions/${moduleName}/${flow}.actions';
import { ${flow}Assertions } from '@/assertions/${moduleName}/${flow}.assertions';

type ${flow}Fixtures = {
  ${flow}: {
    run(): Promise<void>;
    assertions: ${flow}Assertions;
  };
};

export const test = base.extend<${flow}Fixtures>({
  ${flow}: async ({ page }, use) => {
    await ThirdPartyBlocker.block(page);
    const ${pageParam} = new ${pageName}Page(page);
    const actions = new ${flow}Actions(${pageParam});
    const assertions = new ${flow}Assertions(${pageParam});

    await use({
      run: () => actions.run(),
      assertions,
    });
  },
});
`);

  console.log(`\nAnalysis-driven skeleton created for "${flow}" (${segmentNames.length} segments).`);

} else {
  // Empty stub mode

  writeIfNew(paths.component, `import { Page } from '@playwright/test';
import { BaseComponent } from '@/core/base/BaseComponent';

export class ${flow}Component extends BaseComponent {
  constructor(page: Page) {
    super(page, '[data-testid="${kebabCase}"]');
  }

  // Define locators scoped to this component
}
`);

  writeIfNew(paths.page, `import { Page } from '@playwright/test';
import { BasePage } from '@/core/base/BasePage';
import { ${flow}Component } from '@/components/${moduleName}/${flow}.component';

export class ${flow}Page extends BasePage {
  readonly ${camelCase}: ${flow}Component;

  constructor(page: Page) {
    super(page);
    this.${camelCase} = new ${flow}Component(page);
  }
}
`);

  writeIfNew(paths.actions, `import { BaseAction } from '@/core/base/BaseAction';
import { ${flow}Page } from '@/pages/${moduleName}/${flow}Page.page';

export class ${flow}Actions extends BaseAction {
  constructor(private readonly ${camelCase}Page: ${flow}Page) {
    super();
    this.setPage(${camelCase}Page.getPage);
  }

  async run(): Promise<void> {
    // TODO: Implement flow steps (5-15 lines each).
  }
}
`);

  writeIfNew(paths.assertions, `import { expect } from '@playwright/test';
import { ${flow}Page } from '@/pages/${moduleName}/${flow}Page.page';

export class ${flow}Assertions {
  constructor(private readonly ${camelCase}Page: ${flow}Page) {}

  async verifyPageLoaded(): Promise<void> {
    await expect(this.${camelCase}Page.${camelCase}.root).toBeVisible();
  }
}
`);

  writeIfNew(paths.fixture, `import { test as base } from '@playwright/test';
import { ThirdPartyBlocker } from '@/core/sync/ThirdPartyBlocker';
import { ${flow}Page } from '@/pages/${moduleName}/${flow}Page.page';
import { ${flow}Actions } from '@/actions/${moduleName}/${flow}.actions';
import { ${flow}Assertions } from '@/assertions/${moduleName}/${flow}.assertions';

interface ${flow}Fixtures {
  ${camelCase}: {
    actions: ${flow}Actions;
    assertions: ${flow}Assertions;
  };
}

export const test = base.extend<${flow}Fixtures>({
  ${camelCase}: async ({ page }, use) => {
    await ThirdPartyBlocker.block(page);
    const ${camelCase}Page = new ${flow}Page(page);
    const actions = new ${flow}Actions(${camelCase}Page);
    const assertions = new ${flow}Assertions(${camelCase}Page);
    await use({ actions, assertions });
  },
});

export { expect } from '@playwright/test';
`);

  writeIfNew(paths.spec, `import { test, expect } from '../../src/fixtures/${camelCase}.fixture';

test.describe('${flow}', () => {

  test.beforeEach(async ({ page }) => {
    // await page.goto('/${moduleName}/${kebabCase}');
  });

  test('${kebabCase.toUpperCase()}-001 — page loads successfully', async ({ ${camelCase} }) => {
    // await ${camelCase}.assertions.verifyPageLoaded();
  });
});
`);

  console.log(`\nEmpty skeleton created for "${flow}".`);
  console.log(`\nNext steps:`);
  console.log(`  1. Update component locators (data-testid or role-based)`);
  console.log(`  2. Implement action methods for business flows`);
  console.log(`  3. Add assertions for expected behaviors`);
  console.log(`  4. Write test scenarios in the spec file`);
  console.log(`  5. Run: npx tsc --noEmit && npm run lint:caf`);
}
