// Auto-generated by CAF
// T5.2: PR Auto-Comment Bot
// Generates and posts CAF analysis summaries to pull requests

import fs from 'fs';
import { execFileSync } from 'child_process';

// ─────────────────────────────────────────────────────────────────────────────
// Configuration
// ─────────────────────────────────────────────────────────────────────────────

const DATA_SOURCES = {
  releaseConfidence: 'release-confidence.json',
  flakeTriage: 'flake-triage.json',
  lifecycle: '.caf-selector-lifecycle.json',
};

const COMMENT_MARKER = '<!-- CAF-PR-BOT -->';

// ─────────────────────────────────────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────────────────────────────────────

interface CommentSection {
  title: string;
  emoji: string;
  content: string[];
}

interface PRComment {
  sections: CommentSection[];
  summary: string;
  recommendation: 'approve' | 'review' | 'block';
}

// ─────────────────────────────────────────────────────────────────────────────
// Data Loading
// ─────────────────────────────────────────────────────────────────────────────

function loadJson<T>(filePath: string): T | null {
  if (!fs.existsSync(filePath)) return null;
  try {
    return JSON.parse(fs.readFileSync(filePath, 'utf-8'));
  } catch {
    return null;
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// Section Generators
// ─────────────────────────────────────────────────────────────────────────────

interface ReleaseConfidenceData {
  overallScore?: number;
  recommendation?: string;
  summary?: {
    testsRun: number;
    testsPassed: number;
    passRate: number;
    flakeCount: number;
    fallbackRate: number;
  };
  blockers?: string[];
  warnings?: string[];
}

function generateConfidenceSection(data: ReleaseConfidenceData | null): CommentSection {
  if (!data) {
    return { title: 'Release Confidence', emoji: '📊', content: ['No data available.'] };
  }

  const score = data.overallScore || 0;
  const rec = data.recommendation || 'UNKNOWN';
  const recEmoji = rec === 'GO' ? '✅' : rec === 'CAUTION' ? '⚠️' : '❌';

  const content: string[] = [
    '**Score:** ' + score + '/100 ' + recEmoji,
    '**Recommendation:** ' + rec,
    '',
    '| Metric | Value |',
    '|--------|-------|',
    '| Tests | ' + (data.summary?.testsPassed || 0) + '/' + (data.summary?.testsRun || 0) + ' (' + (data.summary?.passRate || 0) + '%) |',
    '| Flakes | ' + (data.summary?.flakeCount || 0) + ' |',
    '| Fallback Rate | ' + (data.summary?.fallbackRate || 0) + '% |',
  ];

  if (data.blockers && data.blockers.length > 0) {
    content.push('', '**Blockers:**');
    for (const b of data.blockers) {
      content.push('- ❌ ' + b);
    }
  }

  if (data.warnings && data.warnings.length > 0) {
    content.push('', '**Warnings:**');
    for (const w of data.warnings) {
      content.push('- ⚠️ ' + w);
    }
  }

  return { title: 'Release Confidence', emoji: '📊', content };
}

interface FlakeTriageData {
  summary?: {
    totalFailures: number;
    autoFixable: number;
    selectorIssues: number;
    byCategory?: Record<string, number>;
  };
  failures?: Array<{
    testName: string;
    failureType: string;
    selector?: string;
    remediation?: { suggestion: string };
  }>;
}

function generateFlakeSection(data: FlakeTriageData | null): CommentSection {
  if (!data || !data.summary) {
    return { title: 'Flake Analysis', emoji: '🔍', content: ['No data available.'] };
  }

  const total = data.summary.totalFailures;

  if (total === 0) {
    return { title: 'Flake Analysis', emoji: '🔍', content: ['✅ No flakes detected!'] };
  }

  const content: string[] = [
    '**Total Flakes:** ' + total,
    '**Auto-Fixable:** ' + data.summary.autoFixable,
    '**Selector Issues:** ' + data.summary.selectorIssues,
  ];

  if (data.summary.byCategory) {
    content.push('', '**By Category:**');
    for (const [cat, count] of Object.entries(data.summary.byCategory)) {
      content.push('- ' + cat + ': ' + count);
    }
  }

  return { title: 'Flake Analysis', emoji: '🔍', content };
}

interface LifecycleData {
  selectors?: Record<string, { state: string }>;
}

function generateLifecycleSection(data: LifecycleData | null): CommentSection {
  if (!data || !data.selectors) {
    return { title: 'Selector Health', emoji: '🎯', content: ['No data available.'] };
  }

  let active = 0;
  let watch = 0;
  let retired = 0;

  for (const s of Object.values(data.selectors)) {
    if (s.state === 'active') active++;
    else if (s.state === 'watch') watch++;
    else if (s.state === 'retired') retired++;
  }

  const total = active + watch + retired;
  const healthRate = total > 0 ? Math.round((active / total) * 100) : 100;
  const healthEmoji = healthRate >= 90 ? '🟢' : healthRate >= 70 ? '🟡' : '🔴';

  const content: string[] = [
    '**Health Rate:** ' + healthRate + '% ' + healthEmoji,
    '',
    '| State | Count |',
    '|-------|-------|',
    '| 🟢 Active | ' + active + ' |',
    '| 🟡 Watch | ' + watch + ' |',
    '| 🔴 Retired | ' + retired + ' |',
  ];

  if (retired > 0) {
    content.push('', '⚠️ ' + retired + ' selector(s) are retired and need replacement.');
  }

  return { title: 'Selector Health', emoji: '🎯', content };
}

// ─────────────────────────────────────────────────────────────────────────────
// Comment Generation
// ─────────────────────────────────────────────────────────────────────────────

function generatePRComment(): PRComment {
  const releaseData = loadJson<ReleaseConfidenceData>(DATA_SOURCES.releaseConfidence);
  const flakeData = loadJson<FlakeTriageData>(DATA_SOURCES.flakeTriage);
  const lifecycleData = loadJson<LifecycleData>(DATA_SOURCES.lifecycle);

  const sections: CommentSection[] = [
    generateConfidenceSection(releaseData),
    generateFlakeSection(flakeData),
    generateLifecycleSection(lifecycleData),
  ];

  const score = releaseData?.overallScore || 100;
  const rec = releaseData?.recommendation || 'GO';
  const flakes = flakeData?.summary?.totalFailures || 0;

  let recommendation: 'approve' | 'review' | 'block' = 'approve';
  let summary = '✅ CAF analysis passed. Ready for merge.';

  if (rec === 'NO-GO' || score < 70) {
    recommendation = 'block';
    summary = '❌ CAF analysis failed. Address blockers before merging.';
  } else if (rec === 'CAUTION' || flakes > 5) {
    recommendation = 'review';
    summary = '⚠️ CAF analysis has warnings. Manual review recommended.';
  }

  return { sections, summary, recommendation };
}

// ─────────────────────────────────────────────────────────────────────────────
// Markdown Rendering
// ─────────────────────────────────────────────────────────────────────────────

function renderMarkdown(comment: PRComment): string {
  const lines: string[] = [
    COMMENT_MARKER,
    '## 🤖 CAF Analysis Report',
    '',
    comment.summary,
    '',
    '---',
    '',
  ];

  for (const section of comment.sections) {
    lines.push('### ' + section.emoji + ' ' + section.title, '');
    lines.push(...section.content);
    lines.push('');
  }

  lines.push('---', '', '*Generated by CAF PR Bot*');
  return lines.join('\n');
}

// ─────────────────────────────────────────────────────────────────────────────
// GitHub Integration
// ─────────────────────────────────────────────────────────────────────────────

function getPRNumber(): string | null {
  // Azure DevOps
  const azurePR = process.env.SYSTEM_PULLREQUEST_PULLREQUESTNUMBER;
  if (azurePR) return azurePR;

  // GitHub Actions
  const ghRef = process.env.GITHUB_REF;
  if (ghRef && ghRef.startsWith('refs/pull/')) {
    const match = ghRef.match(/refs\/pull\/(\d+)/);
    if (match) return match[1];
  }

  // CLI argument
  const prArg = process.argv.find(a => a.startsWith('--pr='));
  if (prArg) return prArg.split('=')[1];

  return null;
}

function postComment(prNumber: string, markdown: string): boolean {
  // Validate prNumber is numeric to prevent command injection
  if (!/^\d+$/.test(prNumber)) {
    console.error('Invalid PR number format: must be numeric');
    return false;
  }

  const tempFile = '.caf-pr-comment.md';
  fs.writeFileSync(tempFile, markdown);

  try {
    // Use execFileSync with args array to prevent command injection
    execFileSync('gh', ['pr', 'comment', prNumber, '--body-file', tempFile], {
      encoding: 'utf-8',
      stdio: 'inherit',
    });
    console.log('✓ Posted CAF comment to PR #' + prNumber);
    return true;
  } catch (error) {
    console.error('Failed to post comment:', error);
    return false;
  } finally {
    if (fs.existsSync(tempFile)) {
      fs.unlinkSync(tempFile);
    }
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// Console Output
// ─────────────────────────────────────────────────────────────────────────────

function printConsoleReport(comment: PRComment, markdown: string): void {
  console.log('═══════════════════════════════════════════════════════════════');
  console.log('  T5.2: PR Auto-Comment Bot');
  console.log('═══════════════════════════════════════════════════════════════');

  const recIcon = comment.recommendation === 'approve' ? '✓' :
    comment.recommendation === 'review' ? '⚠' : '✗';

  console.log('\n' + recIcon + ' Recommendation: ' + comment.recommendation.toUpperCase());
  console.log('\n' + comment.summary);

  console.log('\n───────────────────────────────────────────────────────────────');
  console.log('Generated Markdown Preview:');
  console.log('───────────────────────────────────────────────────────────────');
  console.log(markdown.substring(0, 500) + (markdown.length > 500 ? '...' : ''));
}

// ─────────────────────────────────────────────────────────────────────────────
// CLI Entry Point
// ─────────────────────────────────────────────────────────────────────────────

function main() {
  const args = process.argv.slice(2);
  const dryRun = args.includes('--dry-run');
  const jsonOutput = args.includes('--json');

  // Generate comment
  const comment = generatePRComment();
  const markdown = renderMarkdown(comment);

  // JSON output
  if (jsonOutput) {
    console.log(JSON.stringify({ comment, markdown }, null, 2));
    return;
  }

  // Console report
  printConsoleReport(comment, markdown);

  // Save markdown
  fs.writeFileSync('caf-pr-comment.md', markdown);
  console.log('\n✓ Comment saved to caf-pr-comment.md');

  // Post to PR
  if (!dryRun) {
    const prNumber = getPRNumber();

    if (prNumber) {
      console.log('\nPosting to PR #' + prNumber + '...');
      const success = postComment(prNumber, markdown);

      if (!success) {
        process.exit(1);
      }
    } else {
      console.log('\n⚠ No PR number detected. Use --pr=NUMBER to specify manually.');
      console.log('  Or run in GitHub Actions / Azure DevOps to auto-detect.');
    }
  } else {
    console.log('\n⚠ DRY RUN: Comment not posted. Remove --dry-run to post.');
  }

  // Exit code based on recommendation
  if (comment.recommendation === 'block') {
    process.exit(1);
  }
}

// Guard CLI entry point
if (require.main === module) {
  main();
}

// Exports for testing
export { generatePRComment, renderMarkdown, PRComment };
