// Auto-generated by CAF
// T4.6: Cross-Environment Promotion Scoring
// Calculates confidence scores for promoting selectors between environments

import fs from 'fs';
import { loadEnvironmentSnapshot } from './cross-env-compare';

// ─────────────────────────────────────────────────────────────────────────────
// Configuration
// ─────────────────────────────────────────────────────────────────────────────

const PROMOTION_REPORT_FILE = 'promotion-scoring-report.json';
const MIN_RUNS_FOR_PROMOTION = 10;           // Minimum test runs required
const MIN_SUCCESS_RATE_FOR_PROMOTION = 90;   // Minimum success rate required
const MAX_FALLBACK_RATE_FOR_PROMOTION = 15;  // Maximum fallback rate allowed

type Environment = 'dev' | 'staging' | 'prod';

// ─────────────────────────────────────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────────────────────────────────────

interface PromotionCandidate {
  selector: string;
  sourceEnv: Environment;
  targetEnv: Environment;
  confidenceScore: number;        // 0-100
  factors: {
    successRate: number;
    fallbackRate: number;
    testCoverage: number;         // Based on total runs
    stability: number;            // Based on consecutive successes
    crossEnvConsistency: number;  // Based on comparison with other envs
  };
  eligible: boolean;
  blockers: string[];
  recommendation: string;
}

interface PromotionReport {
  timestamp: string;
  sourceEnv: Environment;
  targetEnv: Environment;
  candidates: PromotionCandidate[];
  summary: {
    totalSelectors: number;
    eligible: number;
    blocked: number;
    avgConfidence: number;
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// Scoring Engine
// ─────────────────────────────────────────────────────────────────────────────

function calculateConfidenceScore(factors: PromotionCandidate['factors']): number {
  // Weighted average of factors
  const weights = {
    successRate: 0.35,
    fallbackRate: 0.20,
    testCoverage: 0.15,
    stability: 0.15,
    crossEnvConsistency: 0.15,
  };

  const score =
    factors.successRate * weights.successRate +
    (100 - factors.fallbackRate) * weights.fallbackRate +
    factors.testCoverage * weights.testCoverage +
    factors.stability * weights.stability +
    factors.crossEnvConsistency * weights.crossEnvConsistency;

  return Math.round(score * 100) / 100;
}

function evaluateSelector(
  selector: string,
  sourceEnv: Environment,
  targetEnv: Environment
): PromotionCandidate | null {
  const sourceSnapshot = loadEnvironmentSnapshot(sourceEnv);

  if (!sourceSnapshot) {
    return null;
  }

  const metrics = sourceSnapshot.selectors[selector];

  if (!metrics) {
    return null;
  }

  const blockers: string[] = [];

  // Factor 1: Success Rate
  const successRate = metrics.successRate;

  if (successRate < MIN_SUCCESS_RATE_FOR_PROMOTION) {
    blockers.push(`Success rate ${successRate}% < ${MIN_SUCCESS_RATE_FOR_PROMOTION}% minimum`);
  }

  // Factor 2: Fallback Rate (lower is better)
  const fallbackRate = metrics.fallbackRate;

  if (fallbackRate > MAX_FALLBACK_RATE_FOR_PROMOTION) {
    blockers.push(`Fallback rate ${fallbackRate}% > ${MAX_FALLBACK_RATE_FOR_PROMOTION}% maximum`);
  }

  // Factor 3: Test Coverage (based on total runs)
  const totalRuns = metrics.totalRuns;
  let testCoverage = 100;

  if (totalRuns < MIN_RUNS_FOR_PROMOTION) {
    testCoverage = (totalRuns / MIN_RUNS_FOR_PROMOTION) * 100;
    blockers.push(`Only ${totalRuns} runs (need ${MIN_RUNS_FOR_PROMOTION})`);
  }

  // Factor 4: Stability (simplified - based on success rate consistency)
  // In a real implementation, this would track success over time
  const stability = successRate >= 95 ? 100 : successRate >= 90 ? 80 : successRate * 0.8;

  // Factor 5: Cross-Environment Consistency
  // Check if target environment already has this selector
  const targetSnapshot = loadEnvironmentSnapshot(targetEnv);
  let crossEnvConsistency = 100;

  if (targetSnapshot && targetSnapshot.selectors[selector]) {
    const targetMetrics = targetSnapshot.selectors[selector];
    const diff = Math.abs(successRate - targetMetrics.successRate);

    if (diff > 20) {
      crossEnvConsistency = 100 - diff;
      blockers.push(`Large variance with ${targetEnv} (${diff.toFixed(1)}% difference)`);
    } else {
      crossEnvConsistency = 100 - diff / 2;  // Slight penalty for small differences
    }
  }

  const factors = {
    successRate,
    fallbackRate,
    testCoverage: Math.round(testCoverage * 100) / 100,
    stability: Math.round(stability * 100) / 100,
    crossEnvConsistency: Math.round(crossEnvConsistency * 100) / 100,
  };

  const confidenceScore = calculateConfidenceScore(factors);
  const eligible = blockers.length === 0;

  let recommendation: string;

  if (eligible && confidenceScore >= 90) {
    recommendation = 'Strongly recommended for promotion';
  } else if (eligible && confidenceScore >= 75) {
    recommendation = 'Recommended for promotion with monitoring';
  } else if (eligible) {
    recommendation = 'Eligible but review recommended';
  } else {
    recommendation = `Blocked: ${blockers[0]}`;
  }

  return {
    selector,
    sourceEnv,
    targetEnv,
    confidenceScore,
    factors,
    eligible,
    blockers,
    recommendation,
  };
}

function generatePromotionReport(
  sourceEnv: Environment,
  targetEnv: Environment
): PromotionReport {
  const sourceSnapshot = loadEnvironmentSnapshot(sourceEnv);

  if (!sourceSnapshot) {
    return {
      timestamp: new Date().toISOString(),
      sourceEnv,
      targetEnv,
      candidates: [],
      summary: {
        totalSelectors: 0,
        eligible: 0,
        blocked: 0,
        avgConfidence: 0,
      },
    };
  }

  const candidates: PromotionCandidate[] = [];

  for (const selector of Object.keys(sourceSnapshot.selectors)) {
    const candidate = evaluateSelector(selector, sourceEnv, targetEnv);

    if (candidate) {
      candidates.push(candidate);
    }
  }

  // Sort by confidence score descending
  candidates.sort((a, b) => b.confidenceScore - a.confidenceScore);

  const eligible = candidates.filter(c => c.eligible);
  const avgConfidence = candidates.length > 0
    ? candidates.reduce((sum, c) => sum + c.confidenceScore, 0) / candidates.length
    : 0;

  return {
    timestamp: new Date().toISOString(),
    sourceEnv,
    targetEnv,
    candidates,
    summary: {
      totalSelectors: candidates.length,
      eligible: eligible.length,
      blocked: candidates.length - eligible.length,
      avgConfidence: Math.round(avgConfidence * 100) / 100,
    },
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// CLI Entry Point
// ─────────────────────────────────────────────────────────────────────────────

function main() {
  const args = process.argv.slice(2);

  const ciMode = args.includes('--ci');
  const verbose = args.includes('--verbose');

  let sourceEnv: Environment = 'dev';
  let targetEnv: Environment = 'staging';

  const sourceIdx = args.indexOf('--from');
  if (sourceIdx !== -1 && args[sourceIdx + 1]) {
    const env = args[sourceIdx + 1] as Environment;
    if (['dev', 'staging', 'prod'].includes(env)) {
      sourceEnv = env;
    }
  }

  const targetIdx = args.indexOf('--to');
  if (targetIdx !== -1 && args[targetIdx + 1]) {
    const env = args[targetIdx + 1] as Environment;
    if (['dev', 'staging', 'prod'].includes(env)) {
      targetEnv = env;
    }
  }

  console.log('═══════════════════════════════════════════════════════════════');
  console.log('  T4.6: Cross-Environment Promotion Scoring');
  console.log('═══════════════════════════════════════════════════════════════');

  console.log(`\nEvaluating: ${sourceEnv} → ${targetEnv}`);

  const report = generatePromotionReport(sourceEnv, targetEnv);

  if (report.candidates.length === 0) {
    console.log('\n⚠ No selectors found in source environment.');
    console.log(`  Capture ${sourceEnv} metrics first: npm run check:cross-env -- --capture --env ${sourceEnv} --url <url>`);
    process.exit(ciMode ? 0 : 1);
  }

  // Display results
  console.log('\n┌──────────────────────────────────────────────────────────────┐');
  console.log('│ Selector                     │ Confidence │ Status    │ Rec │');
  console.log('├──────────────────────────────────────────────────────────────┤');

  const displayCount = verbose ? report.candidates.length : Math.min(report.candidates.length, 15);

  for (let i = 0; i < displayCount; i++) {
    const c = report.candidates[i];
    const selDisplay = c.selector.substring(0, 28).padEnd(28);
    const confDisplay = `${c.confidenceScore}%`.padStart(10);
    const statusDisplay = (c.eligible ? 'ELIGIBLE' : 'BLOCKED').padEnd(9);
    const recDisplay = c.recommendation.substring(0, 3);
    console.log(`│ ${selDisplay} │ ${confDisplay} │ ${statusDisplay} │ ${recDisplay} │`);
  }

  if (!verbose && report.candidates.length > 15) {
    console.log(`│ ... and ${report.candidates.length - 15} more selectors (use --verbose to see all)`);
  }

  console.log('└──────────────────────────────────────────────────────────────┘');

  // Verbose: Show factor breakdown for top candidates
  if (verbose) {
    console.log('\nFactor Breakdown (Top 5):');

    for (const c of report.candidates.slice(0, 5)) {
      console.log(`\n${c.selector}:`);
      console.log(`  Success Rate:     ${c.factors.successRate}%`);
      console.log(`  Fallback Rate:    ${c.factors.fallbackRate}%`);
      console.log(`  Test Coverage:    ${c.factors.testCoverage}%`);
      console.log(`  Stability:        ${c.factors.stability}%`);
      console.log(`  Cross-Env:        ${c.factors.crossEnvConsistency}%`);

      if (c.blockers.length > 0) {
        console.log(`  Blockers:`);
        for (const b of c.blockers) {
          console.log(`    - ${b}`);
        }
      }
    }
  }

  // Summary
  console.log('\nSummary:');
  console.log(`  Total selectors:   ${report.summary.totalSelectors}`);
  console.log(`  Eligible:          ${report.summary.eligible}`);
  console.log(`  Blocked:           ${report.summary.blocked}`);
  console.log(`  Avg confidence:    ${report.summary.avgConfidence}%`);

  // Save report
  fs.writeFileSync(PROMOTION_REPORT_FILE, JSON.stringify(report, null, 2));
  console.log(`\nReport saved to ${PROMOTION_REPORT_FILE}`);

  // CI mode
  if (ciMode) {
    const eligibilityRate = (report.summary.eligible / report.summary.totalSelectors) * 100;

    if (eligibilityRate < 50) {
      console.log(`\n⚠ PROMOTION SCORE: WARNING (only ${eligibilityRate.toFixed(1)}% eligible)`);
    }

    if (report.summary.avgConfidence < 70) {
      console.log('\n✗ PROMOTION SCORE CHECK: FAILED (avg confidence < 70%)');
      process.exit(1);
    }
  }

  console.log('\n✓ PROMOTION SCORING: PASS');
}

// Guard CLI entry point
if (require.main === module) {
  main();
}

// Export for use in other modules
export { generatePromotionReport, evaluateSelector, PromotionCandidate, PromotionReport };
