// Auto-generated by CAF
// T3.7: CI-Integrated Promotion System
// Identifies selectors qualifying for promotion and optionally swaps primary/fallback

import fs from 'fs';
import path from 'path';

// ─────────────────────────────────────────────────────────────────────────────
// Configuration
// ─────────────────────────────────────────────────────────────────────────────

const PROMOTION_THRESHOLD = 40;       // Promote if fallback rate > 40%
const MIN_RUNS_FOR_PROMOTION = 3;     // Minimum runs before considering promotion
const SELECTOR_USAGE_FILE = 'selector-usage.json';
const ANALYSIS_DIR = 'migration-analysis';

// ─────────────────────────────────────────────────────────────────────────────
// Types (aligned with src/core/telemetry/selector-usage.ts schema)
// ─────────────────────────────────────────────────────────────────────────────

interface SelectorUsage {
  fallbackUsed: number;
  primarySuccess: number;
}

interface SelectorCandidate {
  primary: string;
  fallback: string[];
  score: number;
  strategy: string;
  tier: string;
  meta: Record<string, unknown>;
}

interface AnalysisFile {
  pageName: string;
  domain: string;
  generatedAt: string;
  selectors: SelectorCandidate[];
  segments: unknown[];
}

interface PromotionCandidate {
  selector: string;
  fallbackRate: number;
  totalRuns: number;
  fallbackUsed: number;
  recommendedAction: 'promote' | 'review';
}

interface PromotionResult {
  selector: string;
  oldPrimary: string;
  newPrimary: string;
  file: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// Core Logic
// ─────────────────────────────────────────────────────────────────────────────

function loadSelectorUsage(): Map<string, SelectorUsage> {
  if (!fs.existsSync(SELECTOR_USAGE_FILE)) {
    return new Map();
  }

  const data = JSON.parse(fs.readFileSync(SELECTOR_USAGE_FILE, 'utf-8'));
  return new Map(Object.entries(data));
}

function findAnalysisFiles(dir: string): string[] {
  const files: string[] = [];

  if (!fs.existsSync(dir)) {
    return files;
  }

  const entries = fs.readdirSync(dir, { withFileTypes: true });

  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);

    if (entry.isDirectory()) {
      files.push(...findAnalysisFiles(fullPath));
    } else if (entry.name.endsWith('.analysis.json')) {
      files.push(fullPath);
    }
  }

  return files;
}

function identifyPromotionCandidates(
  usageMap: Map<string, SelectorUsage>
): PromotionCandidate[] {
  const candidates: PromotionCandidate[] = [];

  for (const [selector, usage] of usageMap.entries()) {
    // Derive totalRuns from actual schema fields
    const totalRuns = usage.fallbackUsed + usage.primarySuccess;

    if (totalRuns < MIN_RUNS_FOR_PROMOTION) {
      continue;
    }

    const fallbackRate = (usage.fallbackUsed / totalRuns) * 100;

    if (fallbackRate > PROMOTION_THRESHOLD) {
      candidates.push({
        selector,
        fallbackRate: Math.round(fallbackRate * 10) / 10,
        totalRuns,
        fallbackUsed: usage.fallbackUsed,
        recommendedAction: fallbackRate > 60 ? 'promote' : 'review',
      });
    }
  }

  return candidates.sort((a, b) => b.fallbackRate - a.fallbackRate);
}

function applyPromotion(
  filePath: string,
  candidates: PromotionCandidate[],
  dryRun: boolean
): PromotionResult[] {
  const results: PromotionResult[] = [];
  const candidateSet = new Set(
    candidates
      .filter(c => c.recommendedAction === 'promote')
      .map(c => c.selector)
  );

  const content = fs.readFileSync(filePath, 'utf-8');
  const analysis: AnalysisFile = JSON.parse(content);
  let modified = false;

  for (const selector of analysis.selectors) {
    if (!candidateSet.has(selector.primary)) continue;
    if (selector.fallback.length === 0) continue;

    const oldPrimary = selector.primary;
    const newPrimary = selector.fallback[0];

    results.push({
      selector: oldPrimary,
      oldPrimary,
      newPrimary,
      file: filePath,
    });

    // Swap primary and fallback[0]
    selector.fallback[0] = oldPrimary;
    selector.primary = newPrimary;
    modified = true;
  }

  if (modified && !dryRun) {
    // Create backup
    const backupPath = filePath + '.promotion-backup';
    fs.copyFileSync(filePath, backupPath);

    // Write updated analysis
    fs.writeFileSync(filePath, JSON.stringify(analysis, null, 2));
  }

  return results;
}

// ─────────────────────────────────────────────────────────────────────────────
// CLI Entry Point
// ─────────────────────────────────────────────────────────────────────────────

function main() {
  const args = process.argv.slice(2);
  const dryRun = args.includes('--dry-run');
  const applyChanges = args.includes('--apply');
  const ciMode = args.includes('--ci');

  console.log('═══════════════════════════════════════════════════════════════');
  console.log('  T3.7: CI-Integrated Promotion Report');
  console.log('═══════════════════════════════════════════════════════════════');

  // Load telemetry
  const usageMap = loadSelectorUsage();

  if (usageMap.size === 0) {
    console.log('\nNo selector-usage.json found. Nothing to analyze.');
    if (ciMode) {
      console.log('\n✓ PROMOTION CHECK: PASS (no data)');
    }
    process.exit(0);
  }

  console.log(`Loaded ${usageMap.size} selector usage records.`);
  console.log(`Promotion threshold: >${PROMOTION_THRESHOLD}% fallback rate\n`);

  // Identify candidates
  const candidates = identifyPromotionCandidates(usageMap);

  if (candidates.length === 0) {
    console.log('✓ No selectors qualify for promotion.');
    if (ciMode) {
      console.log('\n✓ PROMOTION CHECK: PASS');
    }
    process.exit(0);
  }

  // Report candidates
  console.log('Promotion Candidates:');
  console.log('┌────────────────────────────────────────────────────────────────┐');
  console.log('│ Selector                          │ Rate  │ Runs │ Action     │');
  console.log('├────────────────────────────────────────────────────────────────┤');

  for (const c of candidates) {
    const selectorDisplay = c.selector.substring(0, 33).padEnd(33);
    const rateDisplay = `${c.fallbackRate}%`.padEnd(5);
    const runsDisplay = String(c.totalRuns).padEnd(4);
    const actionDisplay = c.recommendedAction.padEnd(10);

    console.log(`│ ${selectorDisplay} │ ${rateDisplay} │ ${runsDisplay} │ ${actionDisplay} │`);
  }

  console.log('└────────────────────────────────────────────────────────────────┘');

  const promoteCount = candidates.filter(c => c.recommendedAction === 'promote').length;
  const reviewCount = candidates.filter(c => c.recommendedAction === 'review').length;

  console.log(`\nSummary: ${promoteCount} ready for promotion, ${reviewCount} need review`);

  // Apply promotions if requested
  if (applyChanges || dryRun) {
    const analysisFiles = findAnalysisFiles(ANALYSIS_DIR);

    if (analysisFiles.length === 0) {
      console.log(`\nNo analysis files found in ${ANALYSIS_DIR}/`);
    } else {
      console.log(`\n${dryRun ? '[DRY RUN] ' : ''}Applying promotions...`);

      const allResults: PromotionResult[] = [];

      for (const file of analysisFiles) {
        const results = applyPromotion(file, candidates, dryRun);
        allResults.push(...results);
      }

      if (allResults.length > 0) {
        console.log('\nPromotions Applied:');
        for (const r of allResults) {
          console.log(`  ${r.oldPrimary} → ${r.newPrimary}`);
        }

        if (dryRun) {
          console.log('\n⚠ DRY RUN: No files modified. Use --apply to commit changes.');
        } else {
          console.log('\n✓ Analysis files updated. Backups created with .promotion-backup extension.');
        }
      } else {
        console.log('No promotions applied (selectors not found in analysis files or no fallbacks available).');
      }
    }
  }

  // Write report for CI
  const reportPath = 'promotion-report.json';
  fs.writeFileSync(reportPath, JSON.stringify({
    timestamp: new Date().toISOString(),
    threshold: PROMOTION_THRESHOLD,
    minRuns: MIN_RUNS_FOR_PROMOTION,
    candidates,
    summary: {
      total: candidates.length,
      promote: promoteCount,
      review: reviewCount,
    },
  }, null, 2));

  console.log(`\nReport written to ${reportPath}`);

  // CI exit code
  if (ciMode) {
    if (promoteCount > 0) {
      console.log('\n⚠ PROMOTION CHECK: WARNING — selectors need promotion');
      process.exit(0); // Advisory, not blocking
    } else {
      console.log('\n✓ PROMOTION CHECK: PASS');
      process.exit(0);
    }
  }
}

main();
