// Auto-generated by CAF
// T5.6: Pre-Prod Release Confidence Scoring
// Aggregates data from T3/T4/T5 sources to calculate overall release readiness

import fs from 'fs';
import path from 'path';

// ─────────────────────────────────────────────────────────────────────────────
// Configuration
// ─────────────────────────────────────────────────────────────────────────────

const OUTPUT_FILE = 'release-confidence.json';

// Data source files
const DATA_SOURCES = {
  testResults: 'test-results.json',
  flakeTriage: 'flake-triage.json',
  lifecycle: '.caf-selector-lifecycle.json',
  selectorUsage: 'selector-usage.json',
  domDrift: '.caf-dom-snapshots.json',
  promotionScoring: 'promotion-scoring-report.json',
  demotionLog: 'demotion-log.json',
};

// Confidence thresholds
const THRESHOLDS = {
  minTestPassRate: 95,           // Minimum test pass rate for high confidence
  maxFlakeRate: 5,               // Maximum acceptable flake rate
  maxRetiredSelectors: 5,        // Maximum retired selectors
  maxWatchSelectors: 10,         // Maximum selectors in watch state
  maxFallbackRate: 10,           // Maximum overall fallback rate
  maxVolatileSelectors: 5,       // Maximum highly volatile selectors
  minPromotionEligibility: 80,   // Minimum promotion eligibility rate
};

// Scoring weights
const WEIGHTS = {
  testHealth: 0.30,              // Test pass rate
  selectorStability: 0.25,       // Lifecycle state distribution
  flakeControl: 0.20,            // Flake rate and auto-fixability
  fallbackHealth: 0.15,          // Fallback usage patterns
  promotionReadiness: 0.10,      // Cross-env promotion eligibility
};

// ─────────────────────────────────────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────────────────────────────────────

interface ConfidenceFactor {
  name: string;
  score: number;              // 0-100
  weight: number;
  status: 'green' | 'yellow' | 'red';
  details: string;
  blockers?: string[];
}

interface ReleaseConfidenceReport {
  version: string;
  generatedAt: string;
  overallScore: number;       // 0-100
  recommendation: 'GO' | 'CAUTION' | 'NO-GO';
  factors: ConfidenceFactor[];
  summary: {
    testsRun: number;
    testsPassed: number;
    passRate: number;
    totalSelectors: number;
    activeSelectors: number;
    watchSelectors: number;
    retiredSelectors: number;
    flakeCount: number;
    autoFixableFlakes: number;
    fallbackRate: number;
  };
  blockers: string[];
  warnings: string[];
  passCriteria: {
    testPassRate: boolean;
    flakeRate: boolean;
    selectorHealth: boolean;
    fallbackRate: boolean;
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// Data Loading
// ─────────────────────────────────────────────────────────────────────────────

function loadJson<T>(filePath: string): T | null {
  if (!fs.existsSync(filePath)) {
    return null;
  }

  try {
    return JSON.parse(fs.readFileSync(filePath, 'utf-8'));
  } catch {
    return null;
  }
}

interface TestSuiteItem {
  tests?: Array<{
    results: Array<{ status: string }>;
  }>;
  suites?: TestSuiteItem[];
}

interface TestResults {
  suites?: TestSuiteItem[];
}

function loadTestResults(): { total: number; passed: number; failed: number } {
  const results = loadJson<TestResults>(DATA_SOURCES.testResults);

  if (!results) {
    return { total: 0, passed: 0, failed: 0 };
  }

  let total = 0;
  let passed = 0;
  let failed = 0;

  function processSuite(suite: TestSuiteItem) {
    for (const test of suite.tests || []) {
      for (const result of test.results || []) {
        total++;
        if (result.status === 'passed') {
          passed++;
        } else if (result.status === 'failed' || result.status === 'timedOut') {
          failed++;
        }
      }
    }

    for (const childSuite of suite.suites || []) {
      processSuite(childSuite);
    }
  }

  for (const suite of results.suites || []) {
    processSuite(suite);
  }

  return { total, passed, failed };
}

interface FlakeTriageData {
  summary?: {
    totalFailures: number;
    autoFixable: number;
    selectorIssues: number;
  };
}

function loadFlakeTriage(): { total: number; autoFixable: number; selectorIssues: number } {
  const data = loadJson<FlakeTriageData>(DATA_SOURCES.flakeTriage);

  if (!data || !data.summary) {
    return { total: 0, autoFixable: 0, selectorIssues: 0 };
  }

  return {
    total: data.summary.totalFailures,
    autoFixable: data.summary.autoFixable,
    selectorIssues: data.summary.selectorIssues,
  };
}

interface LifecycleData {
  selectors?: Record<string, { state: 'active' | 'watch' | 'retired' }>;
}

function loadLifecycleState(): { active: number; watch: number; retired: number; total: number } {
  const data = loadJson<LifecycleData>(DATA_SOURCES.lifecycle);

  if (!data || !data.selectors) {
    return { active: 0, watch: 0, retired: 0, total: 0 };
  }

  let active = 0;
  let watch = 0;
  let retired = 0;

  for (const selector of Object.values(data.selectors)) {
    if (selector.state === 'active') active++;
    else if (selector.state === 'watch') watch++;
    else if (selector.state === 'retired') retired++;
  }

  return { active, watch, retired, total: active + watch + retired };
}

interface SelectorUsageData {
  [key: string]: { fallbackUsed: number; primarySuccess: number };
}

function loadSelectorUsage(): { totalRuns: number; fallbackRuns: number; rate: number } {
  const data = loadJson<SelectorUsageData>(DATA_SOURCES.selectorUsage);

  if (!data) {
    return { totalRuns: 0, fallbackRuns: 0, rate: 0 };
  }

  let totalRuns = 0;
  let fallbackRuns = 0;

  for (const usage of Object.values(data)) {
    totalRuns += usage.primarySuccess + usage.fallbackUsed;
    fallbackRuns += usage.fallbackUsed;
  }

  const rate = totalRuns > 0 ? (fallbackRuns / totalRuns) * 100 : 0;

  return { totalRuns, fallbackRuns, rate: Math.round(rate * 100) / 100 };
}

interface DomDriftData {
  snapshots?: Record<string, unknown>;
  volatilityScores?: Record<string, number>;
}

function loadDomDrift(): { totalSnapshots: number; volatileCount: number } {
  const data = loadJson<DomDriftData>(DATA_SOURCES.domDrift);

  if (!data) {
    return { totalSnapshots: 0, volatileCount: 0 };
  }

  const snapshots = Object.keys(data.snapshots || {}).length;
  let volatileCount = 0;

  // Count selectors with volatility > 0.7
  for (const score of Object.values(data.volatilityScores || {})) {
    if (score > 0.7) {
      volatileCount++;
    }
  }

  return { totalSnapshots: snapshots, volatileCount };
}

interface PromotionData {
  summary?: {
    totalSelectors: number;
    eligible: number;
  };
}

function loadPromotionScoring(): { total: number; eligible: number; rate: number } {
  const data = loadJson<PromotionData>(DATA_SOURCES.promotionScoring);

  if (!data || !data.summary) {
    return { total: 0, eligible: 0, rate: 100 };  // Default to 100% if no data
  }

  const total = data.summary.totalSelectors;
  const eligible = data.summary.eligible;
  const rate = total > 0 ? (eligible / total) * 100 : 100;

  return { total, eligible, rate: Math.round(rate * 100) / 100 };
}

// ─────────────────────────────────────────────────────────────────────────────
// Scoring Engine
// ─────────────────────────────────────────────────────────────────────────────

function calculateTestHealthScore(passRate: number): ConfidenceFactor {
  let score: number;
  let status: 'green' | 'yellow' | 'red';
  const blockers: string[] = [];

  if (passRate >= THRESHOLDS.minTestPassRate) {
    score = 100;
    status = 'green';
  } else if (passRate >= 85) {
    score = 70 + (passRate - 85);
    status = 'yellow';
    blockers.push(`Pass rate ${passRate.toFixed(1)}% below ${THRESHOLDS.minTestPassRate}% threshold`);
  } else {
    score = passRate;
    status = 'red';
    blockers.push(`Pass rate ${passRate.toFixed(1)}% critically low`);
  }

  return {
    name: 'Test Health',
    score: Math.round(score),
    weight: WEIGHTS.testHealth,
    status,
    details: `Test pass rate: ${passRate.toFixed(1)}%`,
    blockers: blockers.length > 0 ? blockers : undefined,
  };
}

function calculateSelectorStabilityScore(lifecycle: {
  active: number;
  watch: number;
  retired: number;
  total: number;
}): ConfidenceFactor {
  const blockers: string[] = [];

  if (lifecycle.total === 0) {
    return {
      name: 'Selector Stability',
      score: 100,
      weight: WEIGHTS.selectorStability,
      status: 'green',
      details: 'No lifecycle data available (default: healthy)',
    };
  }

  const activeRate = (lifecycle.active / lifecycle.total) * 100;
  let score = activeRate;
  let status: 'green' | 'yellow' | 'red' = 'green';

  // Penalize watch selectors
  if (lifecycle.watch > THRESHOLDS.maxWatchSelectors) {
    score -= (lifecycle.watch - THRESHOLDS.maxWatchSelectors) * 2;
    blockers.push(`${lifecycle.watch} selectors in watch state (max: ${THRESHOLDS.maxWatchSelectors})`);
  }

  // Heavily penalize retired selectors
  if (lifecycle.retired > THRESHOLDS.maxRetiredSelectors) {
    score -= (lifecycle.retired - THRESHOLDS.maxRetiredSelectors) * 5;
    blockers.push(`${lifecycle.retired} retired selectors (max: ${THRESHOLDS.maxRetiredSelectors})`);
  }

  score = Math.max(0, Math.min(100, score));

  if (score < 70) {
    status = 'red';
  } else if (score < 85) {
    status = 'yellow';
  }

  return {
    name: 'Selector Stability',
    score: Math.round(score),
    weight: WEIGHTS.selectorStability,
    status,
    details: `Active: ${lifecycle.active}, Watch: ${lifecycle.watch}, Retired: ${lifecycle.retired}`,
    blockers: blockers.length > 0 ? blockers : undefined,
  };
}

function calculateFlakeControlScore(flakes: {
  total: number;
  autoFixable: number;
  selectorIssues: number;
}, testTotal: number): ConfidenceFactor {
  const blockers: string[] = [];

  if (testTotal === 0) {
    return {
      name: 'Flake Control',
      score: 100,
      weight: WEIGHTS.flakeControl,
      status: 'green',
      details: 'No test data available',
    };
  }

  const flakeRate = (flakes.total / testTotal) * 100;
  let score = 100 - flakeRate * 5;  // Each 1% flake rate costs 5 points
  let status: 'green' | 'yellow' | 'red' = 'green';

  // Bonus for auto-fixable flakes
  if (flakes.total > 0 && flakes.autoFixable > 0) {
    const autoFixRate = flakes.autoFixable / flakes.total;
    score += autoFixRate * 10;  // Up to 10 point bonus
  }

  if (flakeRate > THRESHOLDS.maxFlakeRate) {
    blockers.push(`Flake rate ${flakeRate.toFixed(1)}% exceeds ${THRESHOLDS.maxFlakeRate}% threshold`);
  }

  score = Math.max(0, Math.min(100, score));

  if (score < 70) {
    status = 'red';
  } else if (score < 85) {
    status = 'yellow';
  }

  return {
    name: 'Flake Control',
    score: Math.round(score),
    weight: WEIGHTS.flakeControl,
    status,
    details: `${flakes.total} flakes, ${flakes.autoFixable} auto-fixable`,
    blockers: blockers.length > 0 ? blockers : undefined,
  };
}

function calculateFallbackHealthScore(usage: {
  totalRuns: number;
  fallbackRuns: number;
  rate: number;
}): ConfidenceFactor {
  const blockers: string[] = [];

  if (usage.totalRuns === 0) {
    return {
      name: 'Fallback Health',
      score: 100,
      weight: WEIGHTS.fallbackHealth,
      status: 'green',
      details: 'No usage data available',
    };
  }

  let score = 100 - usage.rate * 2;  // Each 1% fallback rate costs 2 points
  let status: 'green' | 'yellow' | 'red' = 'green';

  if (usage.rate > THRESHOLDS.maxFallbackRate) {
    blockers.push(`Fallback rate ${usage.rate}% exceeds ${THRESHOLDS.maxFallbackRate}% threshold`);
  }

  score = Math.max(0, Math.min(100, score));

  if (score < 70) {
    status = 'red';
  } else if (score < 85) {
    status = 'yellow';
  }

  return {
    name: 'Fallback Health',
    score: Math.round(score),
    weight: WEIGHTS.fallbackHealth,
    status,
    details: `Fallback rate: ${usage.rate}% (${usage.fallbackRuns}/${usage.totalRuns} runs)`,
    blockers: blockers.length > 0 ? blockers : undefined,
  };
}

function calculatePromotionReadinessScore(promotion: {
  total: number;
  eligible: number;
  rate: number;
}): ConfidenceFactor {
  const blockers: string[] = [];

  if (promotion.total === 0) {
    return {
      name: 'Promotion Readiness',
      score: 100,
      weight: WEIGHTS.promotionReadiness,
      status: 'green',
      details: 'No promotion data available',
    };
  }

  const score = promotion.rate;
  let status: 'green' | 'yellow' | 'red' = 'green';

  if (promotion.rate < THRESHOLDS.minPromotionEligibility) {
    blockers.push(
      `Promotion eligibility ${promotion.rate}% below ${THRESHOLDS.minPromotionEligibility}% threshold`
    );
  }

  if (score < 70) {
    status = 'red';
  } else if (score < 85) {
    status = 'yellow';
  }

  return {
    name: 'Promotion Readiness',
    score: Math.round(score),
    weight: WEIGHTS.promotionReadiness,
    status,
    details: `${promotion.eligible}/${promotion.total} selectors eligible for promotion`,
    blockers: blockers.length > 0 ? blockers : undefined,
  };
}

function calculateOverallScore(factors: ConfidenceFactor[]): number {
  let weightedSum = 0;
  let totalWeight = 0;

  for (const factor of factors) {
    weightedSum += factor.score * factor.weight;
    totalWeight += factor.weight;
  }

  return totalWeight > 0 ? Math.round(weightedSum / totalWeight) : 0;
}

function determineRecommendation(
  overallScore: number,
  blockers: string[]
): 'GO' | 'CAUTION' | 'NO-GO' {
  if (blockers.length > 0 || overallScore < 70) {
    return 'NO-GO';
  }

  if (overallScore >= 90) {
    return 'GO';
  }

  return 'CAUTION';
}

// ─────────────────────────────────────────────────────────────────────────────
// Report Generation
// ─────────────────────────────────────────────────────────────────────────────

function generateReport(): ReleaseConfidenceReport {
  // Load all data sources
  const testResults = loadTestResults();
  const flakeTriage = loadFlakeTriage();
  const lifecycle = loadLifecycleState();
  const selectorUsage = loadSelectorUsage();
  const promotion = loadPromotionScoring();

  // Calculate pass rate
  const passRate = testResults.total > 0
    ? (testResults.passed / testResults.total) * 100
    : 100;

  // Calculate confidence factors
  const factors: ConfidenceFactor[] = [
    calculateTestHealthScore(passRate),
    calculateSelectorStabilityScore(lifecycle),
    calculateFlakeControlScore(flakeTriage, testResults.total),
    calculateFallbackHealthScore(selectorUsage),
    calculatePromotionReadinessScore(promotion),
  ];

  // Collect all blockers and warnings
  const blockers: string[] = [];
  const warnings: string[] = [];

  for (const factor of factors) {
    if (factor.blockers) {
      for (const b of factor.blockers) {
        if (factor.status === 'red') {
          blockers.push(b);
        } else {
          warnings.push(b);
        }
      }
    }
  }

  // Calculate overall score
  const overallScore = calculateOverallScore(factors);
  const recommendation = determineRecommendation(overallScore, blockers);

  // Pass criteria
  const passCriteria = {
    testPassRate: passRate >= THRESHOLDS.minTestPassRate,
    flakeRate: (flakeTriage.total / Math.max(testResults.total, 1)) * 100 <= THRESHOLDS.maxFlakeRate,
    selectorHealth: lifecycle.retired <= THRESHOLDS.maxRetiredSelectors,
    fallbackRate: selectorUsage.rate <= THRESHOLDS.maxFallbackRate,
  };

  return {
    version: '1.0',
    generatedAt: new Date().toISOString(),
    overallScore,
    recommendation,
    factors,
    summary: {
      testsRun: testResults.total,
      testsPassed: testResults.passed,
      passRate: Math.round(passRate * 100) / 100,
      totalSelectors: lifecycle.total,
      activeSelectors: lifecycle.active,
      watchSelectors: lifecycle.watch,
      retiredSelectors: lifecycle.retired,
      flakeCount: flakeTriage.total,
      autoFixableFlakes: flakeTriage.autoFixable,
      fallbackRate: selectorUsage.rate,
    },
    blockers,
    warnings,
    passCriteria,
  };
}

function printConsoleReport(report: ReleaseConfidenceReport): void {
  console.log('═══════════════════════════════════════════════════════════════');
  console.log('  T5.6: Pre-Prod Release Confidence Report');
  console.log('═══════════════════════════════════════════════════════════════');

  // Overall recommendation
  const recIcon = report.recommendation === 'GO' ? '✓' :
    report.recommendation === 'CAUTION' ? '⚠' : '✗';
  const recColor = report.recommendation === 'GO' ? 'GREEN' :
    report.recommendation === 'CAUTION' ? 'YELLOW' : 'RED';

  console.log(`\n  ${recIcon}  RECOMMENDATION: ${report.recommendation}  (${recColor})`);
  console.log(`     Overall Score: ${report.overallScore}/100`);

  // Factors breakdown
  console.log('\n───────────────────────────────────────────────────────────────');
  console.log('Confidence Factors:');
  console.log('');

  for (const factor of report.factors) {
    const icon = factor.status === 'green' ? '✓' :
      factor.status === 'yellow' ? '⚠' : '✗';
    const bar = '█'.repeat(Math.floor(factor.score / 10)) +
      '░'.repeat(10 - Math.floor(factor.score / 10));

    console.log(`  ${icon} ${factor.name.padEnd(20)} ${bar} ${factor.score}%`);
    console.log(`    ${factor.details}`);

    if (factor.blockers) {
      for (const b of factor.blockers) {
        console.log(`    └─ ${b}`);
      }
    }
  }

  // Summary
  console.log('\n───────────────────────────────────────────────────────────────');
  console.log('Summary:');
  console.log(`  Tests:     ${report.summary.testsPassed}/${report.summary.testsRun} passed (${report.summary.passRate}%)`);
  console.log(`  Selectors: ${report.summary.activeSelectors} active, ${report.summary.watchSelectors} watch, ${report.summary.retiredSelectors} retired`);
  console.log(`  Flakes:    ${report.summary.flakeCount} total (${report.summary.autoFixableFlakes} auto-fixable)`);
  console.log(`  Fallback:  ${report.summary.fallbackRate}% rate`);

  // Pass criteria
  console.log('\n───────────────────────────────────────────────────────────────');
  console.log('Pass Criteria:');
  console.log(`  ${report.passCriteria.testPassRate ? '✓' : '✗'} Test pass rate ≥ ${THRESHOLDS.minTestPassRate}%`);
  console.log(`  ${report.passCriteria.flakeRate ? '✓' : '✗'} Flake rate ≤ ${THRESHOLDS.maxFlakeRate}%`);
  console.log(`  ${report.passCriteria.selectorHealth ? '✓' : '✗'} Retired selectors ≤ ${THRESHOLDS.maxRetiredSelectors}`);
  console.log(`  ${report.passCriteria.fallbackRate ? '✓' : '✗'} Fallback rate ≤ ${THRESHOLDS.maxFallbackRate}%`);

  // Blockers
  if (report.blockers.length > 0) {
    console.log('\n───────────────────────────────────────────────────────────────');
    console.log('BLOCKERS:');
    for (const b of report.blockers) {
      console.log(`  ✗ ${b}`);
    }
  }

  // Warnings
  if (report.warnings.length > 0) {
    console.log('\n───────────────────────────────────────────────────────────────');
    console.log('Warnings:');
    for (const w of report.warnings) {
      console.log(`  ⚠ ${w}`);
    }
  }

  console.log('\n═══════════════════════════════════════════════════════════════');
}

// ─────────────────────────────────────────────────────────────────────────────
// CLI Entry Point
// ─────────────────────────────────────────────────────────────────────────────

function main() {
  const args = process.argv.slice(2);
  const ciMode = args.includes('--ci');
  const jsonOutput = args.includes('--json');

  // Generate report
  const report = generateReport();

  // Output
  if (jsonOutput) {
    console.log(JSON.stringify(report, null, 2));
  } else {
    printConsoleReport(report);
  }

  // Save report
  fs.writeFileSync(OUTPUT_FILE, JSON.stringify(report, null, 2));

  if (!jsonOutput) {
    console.log(`\nReport saved to ${OUTPUT_FILE}`);
  }

  // CI mode - exit with appropriate code
  if (ciMode) {
    if (report.recommendation === 'NO-GO') {
      console.log('\n✗ RELEASE CONFIDENCE: NO-GO');
      process.exit(1);
    }

    if (report.recommendation === 'CAUTION') {
      console.log('\n⚠ RELEASE CONFIDENCE: CAUTION (manual review required)');
      // Exit 0 but with warning - let CI decide based on workflow
    }

    console.log('\n✓ RELEASE CONFIDENCE: GO');
  }
}

// Guard CLI entry point
if (require.main === module) {
  main();
}

// Exports for testing
export { generateReport, ReleaseConfidenceReport, ConfidenceFactor };
