// Auto-generated by CAF
// T3.2: Score Demotion Pipeline
// Reads runtime fallback telemetry and demotes selector scores in analysis.json

import fs from 'fs';
import path from 'path';

// ─────────────────────────────────────────────────────────────────────────────
// Configuration
// ─────────────────────────────────────────────────────────────────────────────

const FALLBACK_THRESHOLD = 3;        // Demote if fallbackUsed > threshold
const DEMOTION_FACTOR = 0.85;        // Multiply score by this factor
const MIN_SCORE = 50;                // Floor for demoted scores
const SELECTOR_USAGE_FILE = 'selector-usage.json';
const ANALYSIS_DIR = 'migration-analysis';

// ─────────────────────────────────────────────────────────────────────────────
// Types (aligned with src/core/telemetry/selector-usage.ts schema)
// ─────────────────────────────────────────────────────────────────────────────

interface SelectorUsage {
  fallbackUsed: number;
  primarySuccess: number;
}

interface SelectorCandidate {
  primary: string;
  fallback: string[];
  score: number;
  strategy: string;
  tier: string;
  meta: Record<string, unknown>;
}

interface AnalysisFile {
  pageName: string;
  domain: string;
  generatedAt: string;
  selectors: SelectorCandidate[];
  segments: unknown[];
}

interface DemotionResult {
  selector: string;
  oldScore: number;
  newScore: number;
  fallbackCount: number;
  file: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// Core Logic
// ─────────────────────────────────────────────────────────────────────────────

function loadSelectorUsage(): Map<string, SelectorUsage> {
  if (!fs.existsSync(SELECTOR_USAGE_FILE)) {
    console.log('No selector-usage.json found. Nothing to demote.');
    return new Map();
  }

  const data = JSON.parse(fs.readFileSync(SELECTOR_USAGE_FILE, 'utf-8'));
  return new Map(Object.entries(data));
}

function findAnalysisFiles(dir: string): string[] {
  const files: string[] = [];

  if (!fs.existsSync(dir)) {
    return files;
  }

  const entries = fs.readdirSync(dir, { withFileTypes: true });

  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);

    if (entry.isDirectory()) {
      files.push(...findAnalysisFiles(fullPath));
    } else if (entry.name.endsWith('.analysis.json')) {
      files.push(fullPath);
    }
  }

  return files;
}

function demoteScore(currentScore: number): number {
  const demoted = Math.round(currentScore * DEMOTION_FACTOR);
  return Math.max(MIN_SCORE, demoted);
}

function updateTier(score: number): string {
  if (score >= 90) return 'gold';
  if (score >= 75) return 'silver';
  return 'bronze';
}

function processAnalysisFile(
  filePath: string,
  usageMap: Map<string, SelectorUsage>,
  dryRun: boolean
): DemotionResult[] {
  const results: DemotionResult[] = [];

  const content = fs.readFileSync(filePath, 'utf-8');
  const analysis: AnalysisFile = JSON.parse(content);
  let modified = false;

  for (const selector of analysis.selectors) {
    const usage = usageMap.get(selector.primary);

    if (!usage) continue;

    if (usage.fallbackUsed > FALLBACK_THRESHOLD) {
      const oldScore = selector.score;
      const newScore = demoteScore(oldScore);

      if (newScore < oldScore) {
        results.push({
          selector: selector.primary,
          oldScore,
          newScore,
          fallbackCount: usage.fallbackUsed,
          file: filePath,
        });

        selector.score = newScore;
        selector.tier = updateTier(newScore);
        modified = true;
      }
    }
  }

  if (modified && !dryRun) {
    // Create backup
    const backupPath = filePath + '.backup';
    fs.copyFileSync(filePath, backupPath);

    // Write updated analysis
    fs.writeFileSync(filePath, JSON.stringify(analysis, null, 2));
  }

  return results;
}

// ─────────────────────────────────────────────────────────────────────────────
// CLI Entry Point
// ─────────────────────────────────────────────────────────────────────────────

function main() {
  const args = process.argv.slice(2);
  const dryRun = args.includes('--dry-run');
  const verbose = args.includes('--verbose');

  console.log('═══════════════════════════════════════════════════════════════');
  console.log('  T3.2: Score Demotion Pipeline');
  console.log('═══════════════════════════════════════════════════════════════');

  if (dryRun) {
    console.log('Mode: DRY RUN (no files will be modified)\n');
  }

  // Load telemetry
  const usageMap = loadSelectorUsage();

  if (usageMap.size === 0) {
    console.log('\nNo runtime telemetry available. Exiting.');
    process.exit(0);
  }

  console.log(`Loaded ${usageMap.size} selector usage records.`);

  // Find candidates for demotion
  const demotionCandidates = Array.from(usageMap.entries())
    .filter(([_, usage]) => usage.fallbackUsed > FALLBACK_THRESHOLD);

  console.log(`Found ${demotionCandidates.length} selectors exceeding fallback threshold (>${FALLBACK_THRESHOLD}).\n`);

  if (demotionCandidates.length === 0) {
    console.log('✓ All selectors within acceptable fallback limits.');
    process.exit(0);
  }

  // Process analysis files
  const analysisFiles = findAnalysisFiles(ANALYSIS_DIR);

  if (analysisFiles.length === 0) {
    console.log(`No analysis files found in ${ANALYSIS_DIR}/`);
    process.exit(0);
  }

  console.log(`Processing ${analysisFiles.length} analysis file(s)...\n`);

  const allResults: DemotionResult[] = [];

  for (const file of analysisFiles) {
    const results = processAnalysisFile(file, usageMap, dryRun);
    allResults.push(...results);
  }

  // Report
  if (allResults.length === 0) {
    console.log('✓ No demotions needed (selectors not found in analysis files).');
  } else {
    console.log('Demotions:');
    console.log('┌──────────────────────────────────────────────────────────────┐');

    for (const r of allResults) {
      console.log(`│ ${r.selector.substring(0, 40).padEnd(40)} │`);
      console.log(`│   Score: ${r.oldScore} → ${r.newScore} (fallback count: ${r.fallbackCount})`.padEnd(63) + '│');

      if (verbose) {
        console.log(`│   File: ${r.file}`.substring(0, 63).padEnd(63) + '│');
      }
    }

    console.log('└──────────────────────────────────────────────────────────────┘');
    console.log(`\nTotal demotions: ${allResults.length}`);

    if (dryRun) {
      console.log('\n⚠ DRY RUN: No files were modified. Run without --dry-run to apply.');
    } else {
      console.log('\n✓ Analysis files updated. Backups created with .backup extension.');
    }
  }

  // Write demotion log for CI reporting
  const logPath = 'demotion-log.json';
  fs.writeFileSync(logPath, JSON.stringify({
    timestamp: new Date().toISOString(),
    dryRun,
    threshold: FALLBACK_THRESHOLD,
    demotionFactor: DEMOTION_FACTOR,
    demotions: allResults,
  }, null, 2));

  console.log(`\nDemotion log written to ${logPath}`);
}

main();
