// Auto-generated by CAF
// T3.6: Automatic Selector Retirement
// Manages selector lifecycle: active → watch → retired

import fs from 'fs';
import path from 'path';

// ─────────────────────────────────────────────────────────────────────────────
// Configuration
// ─────────────────────────────────────────────────────────────────────────────

const CONSECUTIVE_FALLBACK_THRESHOLD = 5;  // Retire after N consecutive fallbacks
const SCORE_RETIREMENT_THRESHOLD = 50;     // Retire if score drops below this
const SELECTOR_USAGE_FILE = 'selector-usage.json';
const LIFECYCLE_FILE = '.caf-selector-lifecycle.json';
const ANALYSIS_DIR = 'migration-analysis';

// ─────────────────────────────────────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────────────────────────────────────

type LifecycleState = 'active' | 'watch' | 'retired';

interface SelectorLifecycle {
  selector: string;
  state: LifecycleState;
  consecutiveFallbacks: number;
  lastScore: number;
  // Track previous counters to compute deltas
  lastFallbackUsed: number;
  lastPrimarySuccess: number;
  retiredAt?: string;
  retirementReason?: string;
  history: {
    timestamp: string;
    action: string;
  }[];
}

interface LifecycleStore {
  version: string;
  updatedAt: string;
  selectors: Record<string, SelectorLifecycle>;
}

// Aligned with src/core/telemetry/selector-usage.ts schema
interface SelectorUsage {
  fallbackUsed: number;
  primarySuccess: number;
}

interface SelectorCandidate {
  primary: string;
  fallback: string[];
  score: number;
  strategy: string;
  tier: string;
  meta: Record<string, unknown>;
}

interface AnalysisFile {
  pageName: string;
  domain: string;
  generatedAt: string;
  selectors: SelectorCandidate[];
  segments: unknown[];
}

// ─────────────────────────────────────────────────────────────────────────────
// Lifecycle Store
// ─────────────────────────────────────────────────────────────────────────────

function loadLifecycleStore(): LifecycleStore {
  if (!fs.existsSync(LIFECYCLE_FILE)) {
    return {
      version: '1.0',
      updatedAt: new Date().toISOString(),
      selectors: {},
    };
  }

  return JSON.parse(fs.readFileSync(LIFECYCLE_FILE, 'utf-8'));
}

function saveLifecycleStore(store: LifecycleStore): void {
  store.updatedAt = new Date().toISOString();
  fs.writeFileSync(LIFECYCLE_FILE, JSON.stringify(store, null, 2));
}

function getOrCreateLifecycle(
  store: LifecycleStore,
  selector: string
): SelectorLifecycle {
  if (!store.selectors[selector]) {
    store.selectors[selector] = {
      selector,
      state: 'active',
      consecutiveFallbacks: 0,
      lastScore: 100,
      lastFallbackUsed: 0,
      lastPrimarySuccess: 0,
      history: [],
    };
  }
  // Ensure legacy entries have the new fields
  if (store.selectors[selector].lastFallbackUsed === undefined) {
    store.selectors[selector].lastFallbackUsed = 0;
  }
  if (store.selectors[selector].lastPrimarySuccess === undefined) {
    store.selectors[selector].lastPrimarySuccess = 0;
  }
  return store.selectors[selector];
}

// ─────────────────────────────────────────────────────────────────────────────
// Core Logic
// ─────────────────────────────────────────────────────────────────────────────

function loadSelectorUsage(): Map<string, SelectorUsage> {
  if (!fs.existsSync(SELECTOR_USAGE_FILE)) {
    return new Map();
  }

  const data = JSON.parse(fs.readFileSync(SELECTOR_USAGE_FILE, 'utf-8'));
  return new Map(Object.entries(data));
}

function findAnalysisFiles(dir: string): string[] {
  const files: string[] = [];

  if (!fs.existsSync(dir)) {
    return files;
  }

  const entries = fs.readdirSync(dir, { withFileTypes: true });

  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);

    if (entry.isDirectory()) {
      files.push(...findAnalysisFiles(fullPath));
    } else if (entry.name.endsWith('.analysis.json')) {
      files.push(fullPath);
    }
  }

  return files;
}

function collectSelectorsFromAnalysis(): Map<string, number> {
  const selectorScores = new Map<string, number>();
  const analysisFiles = findAnalysisFiles(ANALYSIS_DIR);

  for (const file of analysisFiles) {
    const content = fs.readFileSync(file, 'utf-8');
    const analysis: AnalysisFile = JSON.parse(content);

    for (const selector of analysis.selectors) {
      selectorScores.set(selector.primary, selector.score);
    }
  }

  return selectorScores;
}

function updateLifecycleState(
  lifecycle: SelectorLifecycle,
  usage: SelectorUsage | undefined,
  currentScore: number
): { changed: boolean; reason?: string } {
  const timestamp = new Date().toISOString();

  // Update score
  lifecycle.lastScore = currentScore;

  // Compute deltas from last snapshot (handles cumulative counters correctly)
  if (usage) {
    const fallbackDelta = usage.fallbackUsed - lifecycle.lastFallbackUsed;
    const primaryDelta = usage.primarySuccess - lifecycle.lastPrimarySuccess;

    // Update stored counters for next run
    lifecycle.lastFallbackUsed = usage.fallbackUsed;
    lifecycle.lastPrimarySuccess = usage.primarySuccess;

    // If primary selector succeeded since last run, reset consecutive fallbacks
    if (primaryDelta > 0) {
      lifecycle.consecutiveFallbacks = 0;
    }
    // If only fallbacks occurred (no primary success), increment streak
    else if (fallbackDelta > 0) {
      lifecycle.consecutiveFallbacks += fallbackDelta;
    }
  }

  // State transitions
  const oldState = lifecycle.state;

  // Retirement conditions
  if (lifecycle.state !== 'retired') {
    // Condition 1: Too many consecutive fallbacks
    if (lifecycle.consecutiveFallbacks >= CONSECUTIVE_FALLBACK_THRESHOLD) {
      lifecycle.state = 'retired';
      lifecycle.retiredAt = timestamp;
      lifecycle.retirementReason = `Exceeded consecutive fallback threshold (${lifecycle.consecutiveFallbacks}/${CONSECUTIVE_FALLBACK_THRESHOLD})`;
      lifecycle.history.push({
        timestamp,
        action: `Retired: ${lifecycle.retirementReason}`,
      });
      return { changed: true, reason: lifecycle.retirementReason };
    }

    // Condition 2: Score dropped too low
    if (currentScore < SCORE_RETIREMENT_THRESHOLD) {
      lifecycle.state = 'retired';
      lifecycle.retiredAt = timestamp;
      lifecycle.retirementReason = `Score below threshold (${currentScore}/${SCORE_RETIREMENT_THRESHOLD})`;
      lifecycle.history.push({
        timestamp,
        action: `Retired: ${lifecycle.retirementReason}`,
      });
      return { changed: true, reason: lifecycle.retirementReason };
    }

    // Watch state transition (approaching retirement)
    if (
      lifecycle.consecutiveFallbacks >= CONSECUTIVE_FALLBACK_THRESHOLD / 2 ||
      currentScore < SCORE_RETIREMENT_THRESHOLD + 10
    ) {
      if (lifecycle.state === 'active') {
        lifecycle.state = 'watch';
        lifecycle.history.push({
          timestamp,
          action: 'Moved to watch list',
        });
        return { changed: true };
      }
    }
  }

  return { changed: oldState !== lifecycle.state };
}

function getRetiredSelectors(store: LifecycleStore): string[] {
  return Object.values(store.selectors)
    .filter(s => s.state === 'retired')
    .map(s => s.selector);
}

// ─────────────────────────────────────────────────────────────────────────────
// CLI Entry Point
// ─────────────────────────────────────────────────────────────────────────────

function main() {
  const args = process.argv.slice(2);
  const report = args.includes('--report');
  const listRetired = args.includes('--list-retired');
  const reinstate = args.find(a => a.startsWith('--reinstate='));

  console.log('═══════════════════════════════════════════════════════════════');
  console.log('  T3.6: Selector Lifecycle Management');
  console.log('═══════════════════════════════════════════════════════════════');

  const store = loadLifecycleStore();

  // Handle reinstate command
  if (reinstate) {
    const selector = reinstate.split('=')[1];
    const lifecycle = store.selectors[selector];

    if (!lifecycle) {
      console.log(`\nSelector not found: ${selector}`);
      process.exit(1);
    }

    if (lifecycle.state !== 'retired') {
      console.log(`\nSelector is not retired: ${selector} (state: ${lifecycle.state})`);
      process.exit(1);
    }

    lifecycle.state = 'active';
    lifecycle.consecutiveFallbacks = 0;
    delete lifecycle.retiredAt;
    delete lifecycle.retirementReason;
    lifecycle.history.push({
      timestamp: new Date().toISOString(),
      action: 'Manually reinstated',
    });

    saveLifecycleStore(store);
    console.log(`\n✓ Reinstated: ${selector}`);
    process.exit(0);
  }

  // Handle list-retired command
  if (listRetired) {
    const retired = getRetiredSelectors(store);

    if (retired.length === 0) {
      console.log('\nNo retired selectors.');
    } else {
      console.log(`\nRetired Selectors (${retired.length}):`);
      for (const selector of retired) {
        const lifecycle = store.selectors[selector];
        console.log(`  • ${selector}`);
        console.log(`    Reason: ${lifecycle.retirementReason}`);
        console.log(`    Retired: ${lifecycle.retiredAt}`);
      }
    }
    process.exit(0);
  }

  // Load data
  const usageMap = loadSelectorUsage();
  const selectorScores = collectSelectorsFromAnalysis();

  console.log(`\nLoaded ${usageMap.size} usage records.`);
  console.log(`Found ${selectorScores.size} selectors in analysis files.`);

  // Update lifecycle for all known selectors
  const changes: { selector: string; state: LifecycleState; reason?: string }[] = [];

  for (const [selector, score] of selectorScores.entries()) {
    const lifecycle = getOrCreateLifecycle(store, selector);
    const usage = usageMap.get(selector);
    const result = updateLifecycleState(lifecycle, usage, score);

    if (result.changed) {
      changes.push({
        selector,
        state: lifecycle.state,
        reason: result.reason,
      });
    }
  }

  // Report state counts
  const stateCounts = {
    active: 0,
    watch: 0,
    retired: 0,
  };

  for (const lifecycle of Object.values(store.selectors)) {
    stateCounts[lifecycle.state]++;
  }

  console.log('\nLifecycle Summary:');
  console.log(`  Active:  ${stateCounts.active}`);
  console.log(`  Watch:   ${stateCounts.watch}`);
  console.log(`  Retired: ${stateCounts.retired}`);

  // Report changes
  if (changes.length > 0) {
    console.log('\nState Changes:');
    for (const change of changes) {
      const icon = change.state === 'retired' ? '✗' : change.state === 'watch' ? '⚠' : '✓';
      console.log(`  ${icon} ${change.selector.substring(0, 50)}`);
      console.log(`    → ${change.state}${change.reason ? `: ${change.reason}` : ''}`);
    }
  } else {
    console.log('\nNo state changes.');
  }

  // Save updated store
  saveLifecycleStore(store);
  console.log(`\nLifecycle state saved to ${LIFECYCLE_FILE}`);

  // Detailed report
  if (report) {
    console.log('\n───────────────────────────────────────────────────────────────');
    console.log('Detailed Report:');

    for (const lifecycle of Object.values(store.selectors)) {
      if (lifecycle.state !== 'active') {
        console.log(`\n${lifecycle.selector}:`);
        console.log(`  State: ${lifecycle.state}`);
        console.log(`  Score: ${lifecycle.lastScore}`);
        console.log(`  Consecutive Fallbacks: ${lifecycle.consecutiveFallbacks}`);

        if (lifecycle.history.length > 0) {
          console.log('  History:');
          for (const h of lifecycle.history.slice(-3)) {
            console.log(`    - ${h.timestamp}: ${h.action}`);
          }
        }
      }
    }
  }

  // Exit with warning if new retirements
  const newRetirements = changes.filter(c => c.state === 'retired');
  if (newRetirements.length > 0) {
    console.log(`\n⚠ ${newRetirements.length} selector(s) retired this run.`);
  }
}

// Guard CLI entry point to prevent side effects when imported as a library
if (require.main === module) {
  main();
}

// Export for use in generator
export { loadLifecycleStore, getRetiredSelectors };
