// Auto-generated by CAF
// T5.7: Post-Prod Telemetry Feedback
// Processes production telemetry to improve selector lifecycle decisions

import fs from 'fs';

// ─────────────────────────────────────────────────────────────────────────────
// Configuration
// ─────────────────────────────────────────────────────────────────────────────

const PROD_TELEMETRY_FILE = 'prod-telemetry.json';
const LIFECYCLE_FILE = '.caf-selector-lifecycle.json';
const OUTPUT_FILE = 'telemetry-feedback.json';

// Thresholds for promotion/demotion
const THRESHOLDS = {
  minProdSuccessRate: 98,       // Minimum success rate in prod for promotion
  minProdRuns: 100,             // Minimum runs in prod before making decisions
  maxProdFailureRate: 5,        // Maximum failure rate before demotion
  consecutiveSuccessDays: 7,    // Days of consecutive success for auto-promote
};

// ─────────────────────────────────────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────────────────────────────────────

interface ProdSelectorMetric {
  selector: string;
  totalRuns: number;
  successes: number;
  failures: number;
  lastFailureTimestamp?: string;
  lastSuccessTimestamp?: string;
  consecutiveSuccessDays: number;
  environments: string[];
}

interface ProdTelemetry {
  version: string;
  collectedAt: string;
  environment: string;
  selectors: ProdSelectorMetric[];
}

interface SelectorLifecycle {
  selector: string;
  state: 'active' | 'watch' | 'retired';
  consecutiveFallbacks: number;
  lastScore: number;
  history: Array<{ timestamp: string; action: string }>;
}

interface LifecycleStore {
  version: string;
  updatedAt: string;
  selectors: Record<string, SelectorLifecycle>;
}

interface FeedbackAction {
  selector: string;
  action: 'promote' | 'demote' | 'maintain' | 'review';
  reason: string;
  prodSuccessRate: number;
  prodRuns: number;
  currentState: string;
  suggestedState?: string;
}

interface FeedbackReport {
  version: string;
  generatedAt: string;
  prodEnvironment: string;
  summary: {
    analyzedSelectors: number;
    promotions: number;
    demotions: number;
    maintained: number;
    needsReview: number;
  };
  actions: FeedbackAction[];
  recommendations: string[];
}

// ─────────────────────────────────────────────────────────────────────────────
// Data Loading
// ─────────────────────────────────────────────────────────────────────────────

function loadJson<T>(filePath: string): T | null {
  if (!fs.existsSync(filePath)) {
    return null;
  }

  try {
    return JSON.parse(fs.readFileSync(filePath, 'utf-8'));
  } catch {
    return null;
  }
}

function loadProdTelemetry(): ProdTelemetry | null {
  return loadJson<ProdTelemetry>(PROD_TELEMETRY_FILE);
}

function loadLifecycle(): LifecycleStore | null {
  return loadJson<LifecycleStore>(LIFECYCLE_FILE);
}

// ─────────────────────────────────────────────────────────────────────────────
// Feedback Analysis
// ─────────────────────────────────────────────────────────────────────────────

function analyzeSelector(
  metric: ProdSelectorMetric,
  lifecycle: SelectorLifecycle | undefined
): FeedbackAction {
  const successRate = metric.totalRuns > 0
    ? Math.round((metric.successes / metric.totalRuns) * 100)
    : 100;

  const currentState = lifecycle?.state || 'unknown';

  // Not enough data
  if (metric.totalRuns < THRESHOLDS.minProdRuns) {
    return {
      selector: metric.selector,
      action: 'maintain',
      reason: `Insufficient data: ${metric.totalRuns}/${THRESHOLDS.minProdRuns} minimum runs`,
      prodSuccessRate: successRate,
      prodRuns: metric.totalRuns,
      currentState,
    };
  }

  // High failure rate - demote
  const failureRate = metric.totalRuns > 0
    ? (metric.failures / metric.totalRuns) * 100
    : 0;

  if (failureRate > THRESHOLDS.maxProdFailureRate) {
    return {
      selector: metric.selector,
      action: 'demote',
      reason: `High prod failure rate: ${failureRate.toFixed(1)}% (max: ${THRESHOLDS.maxProdFailureRate}%)`,
      prodSuccessRate: successRate,
      prodRuns: metric.totalRuns,
      currentState,
      suggestedState: currentState === 'active' ? 'watch' : 'retired',
    };
  }

  // Excellent success rate - promote
  if (successRate >= THRESHOLDS.minProdSuccessRate) {
    // Check consecutive success days for watch selectors
    if (currentState === 'watch' && metric.consecutiveSuccessDays >= THRESHOLDS.consecutiveSuccessDays) {
      return {
        selector: metric.selector,
        action: 'promote',
        reason: `Stable in prod: ${successRate}% success over ${metric.consecutiveSuccessDays} consecutive days`,
        prodSuccessRate: successRate,
        prodRuns: metric.totalRuns,
        currentState,
        suggestedState: 'active',
      };
    }

    // Already active or retired with good performance
    if (currentState === 'retired') {
      return {
        selector: metric.selector,
        action: 'review',
        reason: `Retired selector showing ${successRate}% success rate in prod — consider reactivation`,
        prodSuccessRate: successRate,
        prodRuns: metric.totalRuns,
        currentState,
        suggestedState: 'watch',
      };
    }

    return {
      selector: metric.selector,
      action: 'maintain',
      reason: `Healthy in prod: ${successRate}% success rate`,
      prodSuccessRate: successRate,
      prodRuns: metric.totalRuns,
      currentState,
    };
  }

  // Moderate performance - needs review
  return {
    selector: metric.selector,
    action: 'review',
    reason: `Moderate performance: ${successRate}% success rate (below ${THRESHOLDS.minProdSuccessRate}% target)`,
    prodSuccessRate: successRate,
    prodRuns: metric.totalRuns,
    currentState,
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// Lifecycle Updates
// ─────────────────────────────────────────────────────────────────────────────

function applyFeedbackToLifecycle(
  lifecycle: LifecycleStore,
  actions: FeedbackAction[]
): number {
  const timestamp = new Date().toISOString();
  let updated = 0;

  for (const action of actions) {
    if (action.action === 'maintain') continue;
    if (!action.suggestedState) continue;

    const selector = lifecycle.selectors[action.selector];
    if (!selector) continue;

    const newState = action.suggestedState as 'active' | 'watch' | 'retired';
    if (selector.state !== newState) {
      selector.state = newState;
      selector.history.push({
        timestamp,
        action: `Prod telemetry feedback: ${action.reason}`,
      });
      updated++;
    }
  }

  if (updated > 0) {
    lifecycle.updatedAt = timestamp;
    fs.writeFileSync(LIFECYCLE_FILE, JSON.stringify(lifecycle, null, 2));
  }

  return updated;
}

// ─────────────────────────────────────────────────────────────────────────────
// Recommendations Engine
// ─────────────────────────────────────────────────────────────────────────────

function generateRecommendations(actions: FeedbackAction[]): string[] {
  const recommendations: string[] = [];

  const promotionCandidates = actions.filter(a => a.action === 'promote').length;
  const demotionCandidates = actions.filter(a => a.action === 'demote').length;
  const reviewNeeded = actions.filter(a => a.action === 'review').length;

  if (promotionCandidates > 0) {
    recommendations.push(
      `✓ ${promotionCandidates} selector(s) are stable in production and can be promoted to active state`
    );
  }

  if (demotionCandidates > 0) {
    recommendations.push(
      `⚠ ${demotionCandidates} selector(s) have high failure rates in production — consider selector repair`
    );
  }

  if (reviewNeeded > 0) {
    recommendations.push(
      `○ ${reviewNeeded} selector(s) need manual review — moderate performance in production`
    );
  }

  // Calculate overall health
  const totalAnalyzed = actions.length;
  const healthy = actions.filter(a => a.prodSuccessRate >= 95).length;
  const healthRate = totalAnalyzed > 0 ? Math.round((healthy / totalAnalyzed) * 100) : 100;

  if (healthRate >= 95) {
    recommendations.push(`✓ Overall selector health in production: EXCELLENT (${healthRate}%)`);
  } else if (healthRate >= 80) {
    recommendations.push(`○ Overall selector health in production: GOOD (${healthRate}%)`);
  } else {
    recommendations.push(`⚠ Overall selector health in production: NEEDS ATTENTION (${healthRate}%)`);
  }

  // Check for selectors never used in prod
  const lowRunSelectors = actions.filter(a => a.prodRuns < THRESHOLDS.minProdRuns).length;
  if (lowRunSelectors > 0) {
    recommendations.push(
      `○ ${lowRunSelectors} selector(s) have insufficient production data — continue monitoring`
    );
  }

  return recommendations;
}

// ─────────────────────────────────────────────────────────────────────────────
// Report Generation
// ─────────────────────────────────────────────────────────────────────────────

function generateReport(prodData: ProdTelemetry, lifecycle: LifecycleStore | null): FeedbackReport {
  const actions: FeedbackAction[] = [];

  for (const metric of prodData.selectors) {
    const lifecycleEntry = lifecycle?.selectors[metric.selector];
    const action = analyzeSelector(metric, lifecycleEntry);
    actions.push(action);
  }

  const summary = {
    analyzedSelectors: actions.length,
    promotions: actions.filter(a => a.action === 'promote').length,
    demotions: actions.filter(a => a.action === 'demote').length,
    maintained: actions.filter(a => a.action === 'maintain').length,
    needsReview: actions.filter(a => a.action === 'review').length,
  };

  const recommendations = generateRecommendations(actions);

  return {
    version: '1.0',
    generatedAt: new Date().toISOString(),
    prodEnvironment: prodData.environment,
    summary,
    actions,
    recommendations,
  };
}

function printConsoleReport(report: FeedbackReport): void {
  console.log('═══════════════════════════════════════════════════════════════');
  console.log('  T5.7: Post-Prod Telemetry Feedback');
  console.log('═══════════════════════════════════════════════════════════════');

  console.log(`\nEnvironment: ${report.prodEnvironment}`);
  console.log(`Generated: ${new Date(report.generatedAt).toLocaleString()}`);

  console.log('\n───────────────────────────────────────────────────────────────');
  console.log('Summary:');
  console.log(`  Analyzed:     ${report.summary.analyzedSelectors} selectors`);
  console.log(`  Promotions:   ${report.summary.promotions}`);
  console.log(`  Demotions:    ${report.summary.demotions}`);
  console.log(`  Maintained:   ${report.summary.maintained}`);
  console.log(`  Needs Review: ${report.summary.needsReview}`);

  if (report.actions.length > 0) {
    // Show actions by category
    const promotions = report.actions.filter(a => a.action === 'promote');
    const demotions = report.actions.filter(a => a.action === 'demote');
    const reviews = report.actions.filter(a => a.action === 'review');

    if (promotions.length > 0) {
      console.log('\n───────────────────────────────────────────────────────────────');
      console.log('Promotions:');
      for (const a of promotions) {
        console.log(`  ✓ ${a.selector.substring(0, 50)}...`);
        console.log(`    ${a.reason}`);
      }
    }

    if (demotions.length > 0) {
      console.log('\n───────────────────────────────────────────────────────────────');
      console.log('Demotions:');
      for (const a of demotions) {
        console.log(`  ✗ ${a.selector.substring(0, 50)}...`);
        console.log(`    ${a.reason}`);
      }
    }

    if (reviews.length > 0) {
      console.log('\n───────────────────────────────────────────────────────────────');
      console.log('Needs Review:');
      for (const a of reviews) {
        console.log(`  ○ ${a.selector.substring(0, 50)}...`);
        console.log(`    ${a.reason}`);
      }
    }
  }

  console.log('\n───────────────────────────────────────────────────────────────');
  console.log('Recommendations:');
  for (const rec of report.recommendations) {
    console.log(`  ${rec}`);
  }

  console.log('\n═══════════════════════════════════════════════════════════════');
}

// ─────────────────────────────────────────────────────────────────────────────
// Sample Data Generation (for testing when no prod data exists)
// ─────────────────────────────────────────────────────────────────────────────

function generateSampleProdTelemetry(): ProdTelemetry {
  console.log('No prod-telemetry.json found. Generating sample data for demonstration...\n');

  const sampleSelectors: ProdSelectorMetric[] = [
    {
      selector: '[data-testid="login-button"]',
      totalRuns: 1500,
      successes: 1495,
      failures: 5,
      consecutiveSuccessDays: 14,
      environments: ['production'],
    },
    {
      selector: '#save-form-btn',
      totalRuns: 800,
      successes: 720,
      failures: 80,
      consecutiveSuccessDays: 0,
      environments: ['production'],
    },
    {
      selector: '.modal-close:visible',
      totalRuns: 50,
      successes: 48,
      failures: 2,
      consecutiveSuccessDays: 3,
      environments: ['production'],
    },
    {
      selector: '[aria-label="Submit"]',
      totalRuns: 200,
      successes: 198,
      failures: 2,
      consecutiveSuccessDays: 10,
      environments: ['production'],
    },
  ];

  return {
    version: '1.0',
    collectedAt: new Date().toISOString(),
    environment: 'production (sample)',
    selectors: sampleSelectors,
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// CLI Entry Point
// ─────────────────────────────────────────────────────────────────────────────

function main() {
  const args = process.argv.slice(2);
  const applyChanges = args.includes('--apply');
  const jsonOutput = args.includes('--json');
  const useSample = args.includes('--sample');

  console.log('═══════════════════════════════════════════════════════════════');
  console.log('  T5.7: Post-Prod Telemetry Feedback');
  console.log('═══════════════════════════════════════════════════════════════');

  // Load production telemetry
  let prodData = loadProdTelemetry();

  if (!prodData) {
    if (useSample) {
      prodData = generateSampleProdTelemetry();
    } else {
      console.log('\nNo prod-telemetry.json found.');
      console.log('Use --sample flag to generate sample data for demonstration.');
      console.log('\nExpected format:');
      console.log(JSON.stringify({
        version: '1.0',
        collectedAt: '2026-03-16T00:00:00Z',
        environment: 'production',
        selectors: [
          {
            selector: '[data-testid="example"]',
            totalRuns: 1000,
            successes: 990,
            failures: 10,
            consecutiveSuccessDays: 7,
            environments: ['production'],
          },
        ],
      }, null, 2));
      process.exit(0);
    }
  }

  // Load lifecycle
  const lifecycle = loadLifecycle();

  if (!lifecycle) {
    console.log('\nNo .caf-selector-lifecycle.json found.');
    console.log('Run npm run ci:lifecycle first to initialize lifecycle tracking.');
  }

  // Generate report
  const report = generateReport(prodData, lifecycle);

  // Output
  if (jsonOutput) {
    console.log(JSON.stringify(report, null, 2));
  } else {
    printConsoleReport(report);
  }

  // Save report
  fs.writeFileSync(OUTPUT_FILE, JSON.stringify(report, null, 2));

  if (!jsonOutput) {
    console.log(`\n✓ Report saved to ${OUTPUT_FILE}`);
  }

  // Apply changes to lifecycle
  if (applyChanges && lifecycle) {
    const updated = applyFeedbackToLifecycle(lifecycle, report.actions);
    if (updated > 0) {
      console.log(`✓ Applied ${updated} lifecycle state change(s)`);
    } else {
      console.log('○ No lifecycle changes to apply');
    }
  } else if (applyChanges) {
    console.log('⚠ Cannot apply changes: no lifecycle data found');
  }
}

// Guard CLI entry point
if (require.main === module) {
  main();
}

// Exports for testing
export { analyzeSelector, generateRecommendations, FeedbackReport, FeedbackAction };
